#!/bin/bash
apm_zmiana(){
if [ "$apmik" = "stary" ]; then
	sudo chmod a-x /etc/pm/power.d/*
	sudo chmod a+x /etc/pm/power.d/$2
	sudo chown root:root /etc/pm/power.d/*
elif [ "$apmik" = "nowy" ]; then
	if [ "$(ls /sys/class/power_supply/*)" != "" ]; then
		katalog="/etc/udev/rules.d/50-udev-apm-ext73.rules"
	else
	#dodanie apm fixa do rc.local
		katalog="/etc/rc.local"
	fi
	sudo sed -i "s/conservative-conservative/$1/g" $katalog
	sudo sed -i "s/ondemand-ondemand/$1/g" $katalog
	sudo sed -i "s/intel-performance/$1/g" $katalog
	sudo sed -i "s/intel-powersave/$1/g" $katalog
	sudo sed -i "s/performance-conservative/$1/g" $katalog
	sudo sed -i "s/performance-ondemand/$1/g" $katalog
fi
if [ "$wifi_batt_fix" = "FALSE" ];then
	sudo sed -i 's/echo auto > \$ii/echo on > \$ii/g' $katalog_apm
else
	sudo sed -i 's/echo on > \$ii/echo auto > \$ii/g' $katalog_apm
fi

if [ "$bt_batt_on" = "FALSE" ];then
	sudo sed -i 's/echo 1 > \$bt/echo 0 > \$bt/g' $katalog_apm
else
	sudo sed -i 's/echo 0 > \$bt/echo 1 > \$bt/g' $katalog_apm
fi

if [ "$wifi_n_on" = "TRUE" ];then
	sudo rm -f /etc/modprobe.d/wifi_n_on.conf
else
	echo 'options iwlwifi 11n_disable=1' | sudo tee /etc/modprobe.d/wifi_n_on.conf
	echo 'options ath9k nohwcrypt=1'  | sudo tee -a /etc/modprobe.d/wifi_n_on.conf
fi

if [ "$wifi_batt_on" = "FALSE" ];then
	sudo sed -i 's/echo 1 > \$wifi/echo 0 > \$wifi/g' $katalog_apm
else
	sudo sed -i 's/echo 0 > \$wifi/echo 1 > \$wifi/g' $katalog_apm
fi

if [ "$rts5139_on" = "TRUE" ];then
	sudo sed -i '/sudo rmmod rtsx_usb_sdmmc rtsx_usb_ms rtsx_usb/ s/sudo rmmod rtsx_usb_sdmmc rtsx_usb_ms rtsx_usb/sudo modprobe rtsx_usb_sdmmc rtsx_usb_ms rtsx_usb/' $katalog_apm
else
	sudo sed -i '/sudo modprobe rtsx_usb_sdmmc rtsx_usb_ms rtsx_usb/ s/sudo modprobe rtsx_usb_sdmmc rtsx_usb_ms rtsx_usb/sudo rmmod rtsx_usb_sdmmc rtsx_usb_ms rtsx_usb/' $katalog_apm
fi
#intel turbo bateria
if [ "$turbo_batt_on" != "FALSE" ];then
	sudo sed -i 's/echo 1 > \$batintel/echo 0 > \$batintel/g' $katalog_apm
else
	sudo sed -i 's/echo 0 > \$batintel/echo 1 > \$batintel/g' $katalog_apm
fi
#intel turbo AC
if [ "$turbo_ac_on" != "FALSE" ];then
	sudo sed -i 's/echo 1 > \$acintel/echo 0 > \$acintel/g' $katalog_apm
else
	sudo sed -i 's/echo 0 > \$acintel/echo 1 > \$acintel/g' $katalog_apm
fi
#HDD
if [ "$hdd_scheduler" = "bfq" ];then
	sudo sed -i '/#HDD/ s/cfq/bfq/g' $katalog_apm
	sudo sed -i '/#HDD/ s/deadline/bfq/g' $katalog_apm
elif [ "$hdd_scheduler" = "cfq" ];then
	sudo sed -i '/#HDD/ s/bfq/cfq/g' $katalog_apm
	sudo sed -i '/#HDD/ s/deadline/cfq/g' $katalog_apm
elif [ "$hdd_scheduler" = "deadline" ];then
	sudo sed -i '/#HDD/ s/bfq/deadline/g' $katalog_apm
	sudo sed -i '/#HDD/ s/cfq/deadline/g' $katalog_apm
fi
#SSD
if [ "$ssd_scheduler" = "deadline" ];then
	sudo sed -i '/#SSD/ s/noop/deadline/g' $katalog_apm
elif [ "$ssd_scheduler" = "noop" ];then
	sudo sed -i '/#SSD/ s/deadline/noop/g' $katalog_apm
fi
#hibernacja
if [ "$hibernacja_menu" = "TRUE" ];then
	sudo cp /opt/NeteXt73/APM/com.ubuntu.enable-hibernate.pkla /var/lib/polkit-1/localauthority/50-local.d/com.ubuntu.enable-hibernate.pkla -f
else
	if [ -e /var/lib/polkit-1/localauthority/50-local.d/com.ubuntu.enable-hibernate.pkla ]; then
		sudo rm -f /var/lib/polkit-1/localauthority/50-local.d/com.ubuntu.enable-hibernate.pkla
	fi
fi
if [ "$apmik" = "nowy" ]; then
	sudo udevadm control --reload-rules
	sudo /etc/apm-ext73/./$(cat /etc/udev/rules.d/50-udev-apm-ext73.rules | sed 's/.*\///g' | grep adv | head -n 1 | awk '{print $1}')
fi
#zmiana vsync
if [ "$vsync_on" = "FALSE" ]; then
	sudo cp /opt/NeteXt73/APM/drirc /home/$(cat /tmp/netext73/userek)/.drirc -f
	sudo chown $(cat /tmp/netext73/userek):$(cat /tmp/netext73/userek) /home/$(cat /tmp/netext73/userek)/.drirc
else
	sudo rm -f /home/$(cat /tmp/netext73/userek)/.drirc
fi
#samsung_laptop
if [ "$stan_samsung" = "TRUE" ]; then
	sudo rmmod samsung_laptop
	sudo sed -i 's/.*rmmod samsung_laptop/        \/sbin\/rmmod samsung_laptop/g' $katalog_apm
else
	sudo modprobe samsung_laptop
	sudo sed -i 's/.*rmmod samsung_laptop/        # \/sbin\/rmmod samsung_laptop/g' $katalog_apm
fi
}

apm_zmiana_config(){
if [ "$(cat ~/.netext73/apm_status | grep wifi_batt_fix | grep FALSE)" != "" ];then
	sudo sed -i 's/echo auto > \$ii/echo on > \$ii/g' $katalog_apm
else
	sudo sed -i 's/echo on > \$ii/echo auto > \$ii/g' $katalog_apm
fi

if [ "$(cat ~/.netext73/apm_status | grep bt_batt_on | grep FALSE)" != "" ];then
	sudo sed -i 's/echo 1 > \$bt/echo 0 > \$bt/g' $katalog_apm
else
	sudo sed -i 's/echo 0 > \$bt/echo 1 > \$bt/g' $katalog_apm
fi

if [ "$(cat ~/.netext73/apm_status | grep wifi_n_on | grep TRUE)" != "" ];then
	sudo rm -f /etc/modprobe.d/wifi_n_on.conf
else
	echo 'options iwlwifi 11n_disable=1' | sudo tee -a /etc/modprobe.d/wifi_n_on.conf
	echo 'options ath9k nohwcrypt=1'  | sudo tee -a /etc/modprobe.d/wifi_n_on.conf
fi

if [ "$(cat ~/.netext73/apm_status | grep wifi_batt_on | grep FALSE)" != "" ];then
	sudo sed -i 's/echo 1 > \$wifi/echo 0 > \$wifi/g' $katalog_apm
else
	sudo sed -i 's/echo 0 > \$wifi/echo 1 > \$wifi/g' $katalog_apm
fi

#intel turbo bateria
if [ "$(cat ~/.netext73/apm_status | grep turbo_batt_on | grep FALSE)" = "" ];then
	sudo sed -i 's/echo 1 > \$batintel/echo 0 > \$batintel/g' $katalog_apm
	
else
	sudo sed -i 's/echo 0 > \$batintel/echo 1 > \$batintel/g' $katalog_apm
fi
#intel turbo AC
if [ "$(cat ~/.netext73/apm_status | grep turbo_ac_on | grep FALSE)" = "" ];then
	sudo sed -i 's/echo 1 > \$acintel/echo 0 > \$acintel/g' $katalog_apm
else
	sudo sed -i 's/echo 0 > \$acintel/echo 1 > \$acintel/g' $katalog_apm
fi

if [ "$(cat ~/.netext73/apm_status | grep rts5139_on | grep TRUE)" != "" ];then
	sudo sed -i '/sudo rmmod rtsx_usb_sdmmc rtsx_usb_ms rtsx_usb/ s/sudo rmmod rtsx_usb_sdmmc rtsx_usb_ms rtsx_usb/sudo modprobe rtsx_usb_sdmmc rtsx_usb_ms rtsx_usb/' $katalog_apm
	sudo sed -i '1,/sudo modprobe rtsx_usb_sdmmc rtsx_usb_ms rtsx_usb/ s/sudo modprobe rtsx_usb_sdmmc rtsx_usb_ms rtsx_usb/sudo rmmod rtsx_usb_sdmmc rtsx_usb_ms rtsx_usb/' $katalog_apm
else
	sudo sed -i '/sudo modprobe rtsx_usb_sdmmc rtsx_usb_ms rtsx_usb/ s/sudo modprobe rtsx_usb_sdmmc rtsx_usb_ms rtsx_usb/sudo rmmod rtsx_usb_sdmmc rtsx_usb_ms rtsx_usb/' $katalog_apm
fi
#HDD
if [ "$(cat ~/.netext73/apm_status | grep hdd_scheduler | grep bfq)" != "" ];then
	sudo sed -i '/#HDD/ s/cfq/bfq/g' $katalog_apm
	sudo sed -i '/#HDD/ s/deadline/bfq/g' $katalog_apm

elif [ "$(cat ~/.netext73/apm_status | grep hdd_scheduler | grep cfq)" != "" ];then
	sudo sed -i '/#HDD/ s/bfq/cfq/g' $katalog_apm
	sudo sed -i '/#HDD/ s/deadline/cfq/g' $katalog_apm

elif [ "$(cat ~/.netext73/apm_status | grep hdd_scheduler | grep deadline)" != "" ];then
	sudo sed -i '/#HDD/ s/bfq/deadline/g' $katalog_apm
	sudo sed -i '/#HDD/ s/cfq/deadline/g' $katalog_apm
fi
#SSD
if [ "$(cat ~/.netext73/apm_status | grep ssd_scheduler | grep deadline )" != "" ];then
	sudo sed -i '/#SSD/ s/noop/deadline/g' $katalog_apm

elif [ "$(cat ~/.netext73/apm_status | grep ssd_scheduler | grep noop)" != "" ];then
	sudo sed -i '/#SSD/ s/deadline/noop/g' $katalog_apm
fi
#zmiana hibernacji
if [ "$(cat ~/.netext73/apm_status | grep hibernacja | grep TRUE)" != "" ];then
	sudo cp /opt/NeteXt73/APM/com.ubuntu.enable-hibernate.pkla /var/lib/polkit-1/localauthority/50-local.d/com.ubuntu.enable-hibernate.pkla -f
else
	if [ -e /var/lib/polkit-1/localauthority/50-local.d/com.ubuntu.enable-hibernate.pkla ]; then
		sudo rm -f /var/lib/polkit-1/localauthority/50-local.d/com.ubuntu.enable-hibernate.pkla
	fi
fi
if [ "$apmik" = "nowy" ]; then
	sudo udevadm control --reload-rules
	sudo /etc/apm-ext73/./$(cat /etc/udev/rules.d/50-udev-apm-ext73.rules | sed 's/.*\///g' | grep adv | head -n 1 | awk '{print $1}')
fi
#zmiana vsync
if [ "$(cat ~/.netext73/apm_status | grep vsync | grep FALSE)" != "" ];then
	sudo cp /opt/NeteXt73/APM/drirc /home/$(cat /tmp/netext73/userek)/.drirc -f
	sudo chown $(cat /tmp/netext73/userek):$(cat /tmp/netext73/userek) /home/$(cat /tmp/netext73/userek)/.drirc
else
	sudo rm -f /home/$(cat /tmp/netext73/userek)/.drirc
fi
#samsung_laptop
if [ "$(cat ~/.netext73/apm_status | grep stan_samsung | grep TRUE)" != "" ];then
	sudo rmmod samsung_laptop
	sudo sed -i 's/.*rmmod samsung_laptop/        \/sbin\/rmmod samsung_laptop/g' $katalog_apm
else
	sudo modprobe samsung_laptop
	sudo sed -i 's/.*rmmod samsung_laptop/        # \/sbin\/rmmod samsung_laptop/g' $katalog_apm
fi
#jasnosc
if [ "$(cat ~/.netext73/apm_status | grep jasnosc | grep TRUE)" != "" ] && [ "$(ls /sys/class/backlight | head -n 1)" != "" ]; then
		if [ "$(cat /sys/class/power_supply/*/online)" = "0" ];then
			sudo /etc/apm-ext73/./brightness true
		else
			sudo /etc/apm-ext73/./brightness false
		fi
		sudo sed -i 's/.*#SUBSYSTEM/SUBSYSTEM/g' /etc/udev/rules.d/60-brightness-udev-apm-ext73.rules
else
		sudo sed -i 's/.*SUBSYSTEM/#SUBSYSTEM/g' /etc/udev/rules.d/60-brightness-udev-apm-ext73.rules
fi
}