#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury

zmiany_w_APM(){
if [ "$a" != "-" ]; then
	apm_zmiana $a "advanced_power_management_by_ext73_$a*" 
elif [ "$a" = "-" ]; then
	yad --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --text="$TEXT_APM2"
	apm_inst
	if [ -e ~/.netext73/apm_status ]; then
		apm_zmiana_config
	fi
fi
stan_apm_config czeki
}


#########################################################################################################################################################################
#APM

cd /tmp/netext73
rm *.html -f
rm /tmp/netext73/*.txt -f; rm /tmp/netext73/*.sh -f
stan_apm=""
#zapamiętanie configu jeżeli był niepełen config
if [ -e  ~/.netext73/apm_status ] && [ "$(cat ~/.netext73/apm_status | wc -l)" != "12" ]; then
	#sprawdzanie czy jest włączony jakiś APM
	if [ "$apmik" = "stary" ]; then
		if [ "$(ls /etc/pm/power.d/)" != "" ] && [ "$(ls /etc/pm/power.d/advanced_power_management_by_ext73* -Fl | grep '*' | cut -d '_' -f 7)" = "" ];then
			sudo chmod a+x /etc/pm/power.d/advanced_power_management_by_ext73_conservative*
		fi
		#sprawdzenie stanu czeków
		stan_apm_config
	fi
fi
petla_duza="tak"
while [ $petla_duza = "tak" ]; do
	#stan apm config

	stan_apm #sprawdzenie stanu instalacji
	if [ "$stan_apm" = "-" ]; then
		#instalacja APM
		yad --center --question --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="$TEXT_TAK:0" --button="$TEXT_POWROT:1" --text="$TEXT_APM1"
		if [ $? = 0 ]; then
			apm_inst
			if [ -e ~/.netext73/apm_status ]; then
				apm_zmiana_config
			fi
			stan_apm
		fi
	fi

	#sprawdzenie stanu czeków
	stan_apm_config

	aktualny_apm=$(echo $stan_apm | awk '{print $1}')
	menu_apm=$(echo "!conservative-conservative!ondemand-ondemand!intel-performance!intel-powersave!performance-conservative!performance-ondemand" | sed -e "s/$aktualny_apm//" -e 's/!!/!/')
	menu=$(echo "$aktualny_apm$menu_apm" | sed 's/!!/!/')
	
	#ustawienie jasności wg aktualnej
        katalog_jasnosc=$(ls /sys/class/backlight | head -n 1)
        wartsc_bright=$(cat /sys/class/backlight/$katalog_jasnosc/brightness)
        wartosc_max=$(cat /sys/class/backlight/$katalog_jasnosc/max_brightness)
        skala_jasnosci=$wartosc_max

        wartosc_batt=$(cat /etc/apm-ext73/brightness | grep 'echo' | awk '{print $2}' | head -n 1)
        wartosc_ac=$(tac /etc/apm-ext73/brightness | grep 'echo' | awk '{print $2}' | head -n 1)

        wartosc_min=1
        wartosc_max=100
        wartosc_ac=$(awk "BEGIN{print int(($wartosc_max*$wartosc_ac/$skala_jasnosci)+0.5)}")
        wartosc_batt=$(awk "BEGIN{print int(($wartosc_max*$wartosc_batt/$skala_jasnosci)+0.5)}")

        #walidacja
        if [ $wartosc_batt -lt $wartosc_min ]; then
                wartosc_batt=$wartosc_min
        elif [ $wartosc_batt -gt $wartosc_max ]; then
                wartosc_batt=$wartosc_max
        fi
        if [ $wartosc_ac -lt $wartosc_min ]; then
                wartosc_ac=$wartosc_min
        elif [ $wartosc_ac -gt $wartosc_max ]; then
                wartosc_ac=$wartosc_max
        fi

        #sprawdzanie czy jest bateria - włącznik sterowania podświetleniem
        if [ "$(cat /sys/class/power_supply/*/online)" = "" ];then
                jasnosc_dziala="$TEXT_NIE"
        else
                if [ -e /etc/udev/rules.d/60-brightness-udev-apm-ext73.rules ] && [ "$(grep '#SUBSYSTEM' /etc/udev/rules.d/60-brightness-udev-apm-ext73.rules)" = "" ]; then
                        jasnosc_dziala="$TEXT_TAK!$TEXT_NIE"
                else
                        jasnosc_dziala="$TEXT_NIE!$TEXT_TAK"
                fi
	fi
	if [ "$stan_apm" != "-" ]; then
		aa=$(yad --center --columns=2 --title="$nazwa_skryptu" --width=$((410*$skala)) --window-icon="/opt/NeteXt73/ikony/apm.png"  --image="/opt/NeteXt73/ikony/apm.png" --form \
		--field="$TEXT_WERSJA_APM:RO" "$(ls $katalog_apm | cut -d "_" -f 7 | head -n 1)" \
		--field="$TEXT_AKTUALNY_PROFIL_APM:RO" "$aktualny_apm" \
		--field="$TEXT_ZMIEN_PROFIL_APM:CB" "$menu"\
		--field='':LBL "" \
		--field="$TEXT_PLANISTA:CB" "$hdd_scheduler_menu" \
		--field="$(echo $TEXT_PLANISTA | sed 's/HDD/SSD\/FLASH/'):CB" "$ssd_scheduler_menu" \
		--field='':LBL "" \
                --field="$TEXT_STEROWANIE_JASNOSCIA:CB" "$jasnosc_dziala" \
		--field="$TEXT_JASNOSC_NA_BATT:SCL" "$wartosc_batt" \
                --field="$TEXT_JASNOSC_NA_AC:SCL" "$wartosc_ac" \
		--field="$TEXT_FIX1:CHK" "$wifi_batt_fix" \
		--field="$TEXT_FIX2:CHK" "$wifi_batt_on" \
		--field="$TEXT_FIX3:CHK" "$bt_batt_on" \
		--field="$TEXT_FIX4:CHK" "$rts5139_on" \
		--field="$TEXT_FIX5:CHK" "$wifi_n_on" \
		--field='':LBL "" \
		--field="$TEXT_FIX6:CHK" "$turbo_batt_on" \
		--field="$TEXT_FIX7:CHK" "$turbo_ac_on" \
		--field="$TEXT_FIX8:CHK" "$vsync_on" \
		--field="$TEXT_HIBERNACJA:CHK" "$hibernacja_menu" \
		--button="gtk-ok:0" --button="$TEXT_ZAMKNIJ:1" )

		klawisz=$?
		if [ $klawisz = 0 ]; then
			a=$(echo $aa | cut -d "|" -f 3)
			export hdd_scheduler=$(echo $aa | cut -d "|" -f 5)
			export ssd_scheduler=$(echo $aa | cut -d "|" -f 6)
			
			export jasnosc_dziala=$(echo $aa | cut -d "|" -f 8)
			export wart_batt1=$(echo $aa | cut -d "|" -f 9)
			export wart_ac1=$(echo $aa | cut -d "|" -f 10)
			
			export wifi_batt_fix=$(echo $aa | cut -d "|" -f 11)
			export wifi_batt_on=$(echo $aa | cut -d "|" -f 12)
			export bt_batt_on=$(echo $aa | cut -d "|" -f 13)
			export rts5139_on=$(echo $aa | cut -d "|" -f 14)
			export wifi_n_on=$(echo $aa | cut -d "|" -f 15)
			
			export turbo_batt_on=$(echo $aa | cut -d "|" -f 17)
			export turbo_ac_on=$(echo $aa | cut -d "|" -f 18)
			
			export vsync_on=$(echo $aa | cut -d "|" -f 19)
			export hibernacja_menu=$(echo $aa | cut -d "|" -f 20)
			
			
			wart_batt=$(awk "BEGIN{print int(($wart_batt1*$skala_jasnosci/$wartosc_max)+0.5)}")
                        wart_ac=$(awk "BEGIN{print int(($wart_ac1*$skala_jasnosci/$wartosc_max)+0.5)}")
                        sudo sed -i "/#ac/ s/echo.*>/echo $wart_ac >/" /etc/apm-ext73/brightness
                        sudo sed -i "/#bateria/ s/echo.*>/echo $wart_batt >/" /etc/apm-ext73/brightness
                        if [ "$(cat /sys/class/power_supply/*/online)" = "0" ];then
                                sudo /etc/apm-ext73/./brightness true
                        else
                                sudo /etc/apm-ext73/./brightness false
                        fi
                        if [ "$jasnosc_dziala" = "$TEXT_TAK" ]; then
                                #if [ "$(echo $wart | cut -d "|" -f 1)" = "TRUE" ];then
                                        sudo sed -i 's/#SUBSYSTEM/SUBSYSTEM/g' /etc/udev/rules.d/60-brightness-udev-apm-ext73.rules
                        else
                                        sudo sed -i 's/SUBSYSTEM/#SUBSYSTEM/g' /etc/udev/rules.d/60-brightness-udev-apm-ext73.rules
                                #fi
                        fi
			
			
			
			#uruchomienie aktualizacji gdy zaszła jakaś zmiana
			if [ "$hdd_scheduler" = "blk-mq" ] || [ "$ssd_scheduler" = "blk-mq" ]; then
				if [ "$a" = "$aktualny_apm" ] && [ "$wifi_batt_fix_przed" = "$wifi_batt_fix" ] && [ "$wifi_batt_on_przed" = "$wifi_batt_on" ] && [ "$bt_batt_on_przed" = "$bt_batt_on" ] && [ "$rts5139_on_przed" = "$rts5139_on" ] && [ "$wifi_n_on_przed" = "$wifi_n_on" ] && [ "$turbo_batt_on_przed" = "$turbo_batt_on" ] && [ "$turbo_ac_on_przed" = "$turbo_ac_on" ] && [ "$hibernacja_menu_przed" = "$hibernacja_menu" ] && [ "$vsync_on_przed" = "$vsync_on" ]; then
					opusc_petle
				else
					zmiany_w_APM
				fi
			else
				if [ "$a" = "$aktualny_apm" ] && [ "$wifi_batt_fix_przed" = "$wifi_batt_fix" ] && [ "$wifi_batt_on_przed" = "$wifi_batt_on" ] && [ "$bt_batt_on_przed" = "$bt_batt_on" ] && [ "$rts5139_on_przed" = "$rts5139_on" ] && [ "$wifi_n_on_przed" = "$wifi_n_on" ] && [ "$hdd_scheduler_przed" = "$hdd_scheduler" ] && [ "$ssd_scheduler_przed" = "$ssd_scheduler" ] && [ "$turbo_batt_on_przed" = "$turbo_batt_on" ] && [ "$turbo_ac_on_przed" = "$turbo_ac_on" ] && [ "$hibernacja_menu_przed" = "$hibernacja_menu" ]  && [ "$vsync_on_przed" = "$vsync_on" ]; then
					opusc_petle
				else
					zmiany_w_APM
				fi
			fi
                        
		fi
	fi
	if [ -z "$aa" ]; then
		opusc_petle
	fi
done

