#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury

zmiany_w_APM(){
if [ "$a" != "-" ]; then
	apm_zmiana $a "advanced_power_management_by_ext73_$a*"
elif [ "$a" = "-" ]; then
	yad --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --text="$TEXT_APM2"
	apm_inst
fi
stan_apm_config czeki
}


#########################################################################################################################################################################
#APM

cd /tmp/netext73

rm *.html -f
rm /tmp/netext73/*.txt -f; rm /tmp/netext73/*.sh -f
stan_apm=""


#sprawdzanie czy była zmiana blk-mq
if [ "$(grep 'GRUB_CMDLINE_LINUX' /etc/default/grub | grep 'scsi_mod.use_blk_mq=1')" != "" ]; then
	if [ "$(cat /etc/netext73/apm_status | grep -E "none|mq-deadline|kyber|bfq")" = "" ] || [ "$(cat $katalog_apm | grep '#HDD' | grep -E "none|mq-deadline|kyber|bfq")" = "" ] || [ "$(cat $katalog_apm | grep '#SSD' | grep -E "none|mq-deadline|kyber|bfq")" = "" ] ;then
		sed -i 's/hdd_scheduler.*/hdd_scheduler		none/g' /etc/netext73/apm_status
		sed -i 's/ssd_scheduler.*/ssd_scheduler		none/g' /etc/netext73/apm_status
		sudo sed -i "/#HDD/ s/echo.*>/echo none >/g" $katalog_apm
		sudo sed -i "/#SSD/ s/echo.*>/echo none >/g" $katalog_apm
		for i in /sys/block/sd*/queue; do
			echo none > $i/scheduler 
		done
	fi
else
	if [ "$(cat /etc/netext73/apm_status | grep -E "noop|cfq|bfq|deadline")" = "" ] || [ "$(cat $katalog_apm | grep '#HDD' | grep -E  "noop|cfq|bfq|deadline")" = "" ]  || [ "$(cat $katalog_apm | grep '#SSD' | grep -E  "noop|cfq|bfq|deadline")" = "" ];then
		sed -i 's/hdd_scheduler.*/hdd_scheduler		noop/g' /etc/netext73/apm_status
		sed -i 's/ssd_scheduler.*/ssd_scheduler		noop/g' /etc/netext73/apm_status
		sudo sed -i "/#HDD/ s/echo.*>/echo noop >/g" $katalog_apm
		sudo sed -i "/#SSD/ s/echo.*>/echo noop >/g" $katalog_apm
		for i in /sys/block/sd*/queue; do
			echo noop > $i/scheduler 
		done
	fi
fi

#zapamiętanie configu jeżeli był niepełen config
if [ -e  /etc/netext73/apm_status ] && [ "$(cat /etc/netext73/apm_status | wc -l)" != "14" ]; then
	#sprawdzanie czy jest włączony jakiś APM
	if [ "$apmik" = "stary" ]; then
		if [ -e /etc/pm/power.d ] && [ "$(ls /etc/pm/power.d | grep advanced_power_management_by_ext73)" != "" ] && [ "$(ls /etc/pm/power.d/advanced_power_management_by_ext73* -Fl | grep '*' | cut -d '_' -f 7)" = "" ];then
			sudo chmod a+x /etc/pm/power.d/advanced_power_management_by_ext73_conservative*
		fi
		#sprawdzenie stanu czeków
		stan_apm_config
	fi
fi
petla_duza="tak"
while [ $petla_duza = "tak" ]; do
	#stan apm config

	stan_apm #sprawdzenie stanu instalacji
	if [ "$stan_apm" = "-" ]; then
		#instalacja APM
		yad --center --question --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="$TEXT_TAK:0" --button="$TEXT_POWROT:1" --text="$TEXT_APM1"
		if [ $? = 0 ]; then
			apm_inst
			stan_apm
		fi
	fi

	#sprawdzenie stanu czeków
	stan_apm_config

	aktualny_apm=$(echo $stan_apm | awk '{print $1}')
	if [ "$(grep -i pstate /sys/devices/system/cpu/cpu*/cpufreq/scaling_driver)" != "" ] && [ "$(cat /proc/cpuinfo | grep -i 'model name' | grep -E "i3-|i5-|i7-|e3-|e5-|e7-")" != "" ]; then
		#wybór APM dla pstate
		menu_apm=$(echo "intel-performance!intel-powersave" | sed -e "s/$aktualny_apm//" -e 's/!!/!/')
	else
		#wybór APM dla pozostałych
		menu_apm=$(echo "conservative-conservative!ondemand-ondemand!performance-conservative!performance-ondemand" | sed -e "s/$aktualny_apm//" -e 's/!!/!/')
	fi
	menu=$(echo "$aktualny_apm!$menu_apm" | sed -e 's/!!/!/' -e 's/!$//')

	#ustawienie jasności wg aktualnej
        katalog_jasnosc=$(ls /sys/class/backlight | head -n 1)
        if [ "$katalog_jasnosc" != "" ]; then
		wartsc_bright=$(cat /sys/class/backlight/$katalog_jasnosc/brightness)
		wartosc_max=$(cat /sys/class/backlight/$katalog_jasnosc/max_brightness)
		skala_jasnosci=$wartosc_max

		wartosc_batt=$(cat /etc/apm-ext73/brightness | grep 'echo' | awk '{print $2}' | head -n 1)
		wartosc_ac=$(tac /etc/apm-ext73/brightness | grep 'echo' | awk '{print $2}' | head -n 1)

		wartosc_min=1
		wartosc_max=100
		wartosc_ac=$(awk "BEGIN{print int(($wartosc_max*$wartosc_ac/$skala_jasnosci)+0.5)}")
		wartosc_batt=$(awk "BEGIN{print int(($wartosc_max*$wartosc_batt/$skala_jasnosci)+0.5)}")

		#walidacja
		if [ $wartosc_batt -lt $wartosc_min ]; then
			wartosc_batt=$wartosc_min
		elif [ $wartosc_batt -gt $wartosc_max ]; then
			wartosc_batt=$wartosc_max
		fi
		if [ $wartosc_ac -lt $wartosc_min ]; then
			wartosc_ac=$wartosc_min
		elif [ $wartosc_ac -gt $wartosc_max ]; then
			wartosc_ac=$wartosc_max
		fi
	else
		wartosc_batt="2"
		wartosc_ac="8"
	fi


	if [ "$stan_apm" != "-" ]; then
		aa=$(yad --center --on-top --columns=2 --title="$nazwa_skryptu" --width=$((410*$skala)) --window-icon="/opt/NeteXt73/ikony/apm.png"  --image="/opt/NeteXt73/ikony/apm.png" --form \
		--field="$TEXT_WERSJA_APM:RO" "$(ls $katalog_apm | cut -d "_" -f 7 | head -n 1)" \
		--field="$TEXT_AKTUALNY_PROFIL_APM:RO" "$aktualny_apm" \
		--field="$TEXT_ZMIEN_PROFIL_APM:CB" "$menu"\
		--field='':LBL "" \
		--field="$TEXT_PLANISTA:CB" "$hdd_scheduler_menu" \
		--field="$(echo $TEXT_PLANISTA | sed 's/HDD/SSD\/FLASH/'):CB" "$ssd_scheduler_menu" \
		--field='':LBL "" \
        --field="$TEXT_STEROWANIE_JASNOSCIA:CHK" "$jasnosc_dziala" \
		--field="$TEXT_JASNOSC_NA_BATT:SCL" "$wartosc_batt" \
        --field="$TEXT_JASNOSC_NA_AC:SCL" "$wartosc_ac" \
        --field='':LBL "" \
		--field="$TEXT_FIX1:CHK" "$wifi_batt_fix" \
		--field="$TEXT_FIX2:CHK" "$wifi_batt_on" \
		--field="$TEXT_FIX3:CHK" "$bt_batt_on" \
		--field="$TEXT_FIX4:CHK" "$rts5139_on" \
		--field="$TEXT_FIX5:CHK" "$wifi_n_on" \
		--field="$TEXT_FIX6:CHK" "$turbo_batt_on" \
		--field="$TEXT_FIX7:CHK" "$turbo_ac_on" \
		--field="$TEXT_FIX8:CHK" "$vsync_on" \
		--field="$TEXT_HIBERNACJA:CHK" "$hibernacja_menu" \
		--field="$TEXT_SAMSUNG:CHK" "$stan_samsung" \
		--field="$TEXT_FIX9:CHK" "$stan_min_free_kbytes" \
		--button="gtk-ok:0" --button="CPU-FREQ:2" --button="$TEXT_ZAMKNIJ:1" )
		klawisz=$?
		if [ $klawisz = 0 ]; then
			a=$(echo $aa | cut -d "|" -f 3)
			export hdd_scheduler=$(echo $aa | cut -d "|" -f 5)
			export ssd_scheduler=$(echo $aa | cut -d "|" -f 6)

			export jasnosc_dziala=$(echo $aa | cut -d "|" -f 8)
			export wart_batt1=$(echo $aa | cut -d "|" -f 9)
			export wart_ac1=$(echo $aa | cut -d "|" -f 10)

			export wifi_batt_fix=$(echo $aa | cut -d "|" -f 12)
			export wifi_batt_on=$(echo $aa | cut -d "|" -f 13)
			export bt_batt_on=$(echo $aa | cut -d "|" -f 14)
			export rts5139_on=$(echo $aa | cut -d "|" -f 15)
			export wifi_n_on=$(echo $aa | cut -d "|" -f 16)

			export turbo_batt_on=$(echo $aa | cut -d "|" -f 17)
			export turbo_ac_on=$(echo $aa | cut -d "|" -f 18)

			export vsync_on=$(echo $aa | cut -d "|" -f 19)
			export hibernacja_menu=$(echo $aa | cut -d "|" -f 20)
			export stan_samsung=$(echo $aa | cut -d "|" -f 21)
			export stan_min_free_kbytes=$(echo $aa | cut -d "|" -f 22)
			if [ "$jasnosc_dziala" = "TRUE" ] && [ "$katalog_jasnosc" != "" ]; then
				wart_batt=$(awk "BEGIN{print int(($wart_batt1*$skala_jasnosci/$wartosc_max)+0.5)}")
				wart_ac=$(awk "BEGIN{print int(($wart_ac1*$skala_jasnosci/$wartosc_max)+0.5)}")
				sudo sed -i "/#ac/ s/echo.*>/echo $wart_ac >/" /etc/apm-ext73/brightness
				sudo sed -i "/#bateria/ s/echo.*>/echo $wart_batt >/" /etc/apm-ext73/brightness
				if [ "$(cat /sys/class/power_supply/*/online)" = "0" ];then
					sudo /etc/apm-ext73/./brightness true
				else
					sudo /etc/apm-ext73/./brightness false
				fi
				sudo sed -i 's/.*#SUBSYSTEM/SUBSYSTEM/g' /etc/udev/rules.d/60-brightness-udev-apm-ext73.rules
			else
			#jasnosc_dziala="FALSE"
				sudo sed -i 's/.*SUBSYSTEM/#SUBSYSTEM/g' /etc/udev/rules.d/60-brightness-udev-apm-ext73.rules
			fi
			#uruchomienie aktualizacji gdy zaszła jakaś zmiana
			if [ "$hdd_scheduler" = "blk-mq" ] || [ "$ssd_scheduler" = "blk-mq" ]; then
				if  [ "$jasnosc_dziala_przed" = "$jasnosc_dziala" ] && [ "$a" = "$aktualny_apm" ] && [ "$wifi_batt_fix_przed" = "$wifi_batt_fix" ] && [ "$wifi_batt_on_przed" = "$wifi_batt_on" ] && [ "$bt_batt_on_przed" = "$bt_batt_on" ] && [ "$rts5139_on_przed" = "$rts5139_on" ] && [ "$wifi_n_on_przed" = "$wifi_n_on" ] && [ "$turbo_batt_on_przed" = "$turbo_batt_on" ] && [ "$turbo_ac_on_przed" = "$turbo_ac_on" ] && [ "$hibernacja_menu_przed" = "$hibernacja_menu" ] && [ "$vsync_on_przed" = "$vsync_on" ] && [ "$stan_samsung_przed" = "$stan_samsung" ] && [ "$stan_min_free_kbytes_przed" = "$stan_min_free_kbytes" ]; then
					opusc_petle
				else
					zmiany_w_APM
				fi
			else
				if  [ "$jasnosc_dziala_przed" = "$jasnosc_dziala" ] && [ "$a" = "$aktualny_apm" ] && [ "$wifi_batt_fix_przed" = "$wifi_batt_fix" ] && [ "$wifi_batt_on_przed" = "$wifi_batt_on" ] && [ "$bt_batt_on_przed" = "$bt_batt_on" ] && [ "$rts5139_on_przed" = "$rts5139_on" ] && [ "$wifi_n_on_przed" = "$wifi_n_on" ] && [ "$hdd_scheduler_przed" = "$hdd_scheduler" ] && [ "$ssd_scheduler_przed" = "$ssd_scheduler" ] && [ "$turbo_batt_on_przed" = "$turbo_batt_on" ] && [ "$turbo_ac_on_przed" = "$turbo_ac_on" ] && [ "$hibernacja_menu_przed" = "$hibernacja_menu" ]  && [ "$vsync_on_przed" = "$vsync_on" ] && [ "$stan_samsung_przed" = "$stan_samsung" ] && [ "$stan_min_free_kbytes_przed" = "$stan_min_free_kbytes" ]; then
					opusc_petle
				else
					zmiany_w_APM
				fi
			fi
		elif [ $klawisz = 2 ]; then
			petla_duza="tak"
			while [ $petla_duza = "tak" ]; do
				cpu_min=$(( $(cat /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_min_freq | head -n 1) /1000 ))
				cpu_max=$(( $(cat /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_max_freq | head -n 1) / 1000 ))
				cpu_current=$(( $(cat  /sys/devices/system/cpu/cpu*/cpufreq/scaling_max_freq | head -n 1) / 1000 ))
				aa=$(yad --scale --text="$TEXT_CPU_MAX_FREQ \n" --center --on-top \
				--title="$nazwa_skryptu" --width=$((410*$skala)) --window-icon="/opt/NeteXt73/ikony/monitor.png" --image="/opt/NeteXt73/ikony/monitor.png" \
				--value=$cpu_current --min-value=$cpu_min --max-value=$cpu_max --mark="$cpu_min"Mhz:$cpu_min --mark="$cpu_max"MHz:$cpu_max --mark=$(($(($cpu_min+$cpu_max))/2))MHz:$(($((cpu_min+$cpu_max))/2)) \
				--button="gtk-ok:0" --button="$TEXT_ZAMKNIJ:1")
				klawisz=$?
				if [ $klawisz = 0 ]; then
					wartosc=$(echo $aa | cut -d "|" -f 1)
					if [ "$wartosc" = "$cpu_current" ]; then
						opusc_petle
					else
						for i in $(ls /sys/devices/system/cpu/ | grep cpu[0-9]); do
							echo $(( $wartosc * 1000 )) > /sys/devices/system/cpu/$i/cpufreq/scaling_max_freq
						done
					fi
				else
					opusc_petle
				fi
			done
		fi
	fi
	if [ -z "$aa" ]; then
		opusc_petle
	fi
done
