#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury

#########################################################################################################################################################################
#instalator płatnych wersji

cd /tmp/netext73
wymagana_instalacja_nv(){
#wymagana reinstalacja sterowników NV
if  [ "$a5" != "TRUE" ] && { [ "$(lspci | grep -i GeForce | grep -i NVIDIA)" != "" ] || [ "$(lspci | grep -i NVIDIA | grep -i Quadro)" != "" ]; }; then
	dymek  -i $warning1 "$TEXT_UWAGA" "$TEXT_WYMAGANY_NV"
	/opt/NeteXt73/./grafiki nvidia
fi
}
if [ -e /etc/netext73/kernel_automat ] && [ -e /etc/netext73/instalator_kerneli ] && [ "$(cat /etc/netext73/kernel_automat)" = "TRUE" ]; then
	kern="$(cat /etc/netext73/instalator_kerneli)"
	if [ "$(echo $kern | grep -E $lista_kerneli_premium)" != "" ]; then
		export premium="tak"
	else
		export premium="nie"
	fi
else
	if [ "$1" = "standard" ];then
		if [ "$komputerek" = "INTEL" ]; then
			kern="intelstandard"
		elif [ "$komputerek" = "AMD" ]; then
			kern="amdstandard"
		fi
		export premium="nie"
	elif [ "$(echo $1 | grep -E $lista_kerneli_premium)" != "" ]; then
		kern="$1"
		export premium="tak"
	fi
	#szerokość i wysokość dla premium
	szer="720"
	if [ "$skala" = "2" ];then
		wysokosc="400"
	else
		wysokosc="300"
	fi
	if [ "$1" = "premium" ] && [ "$komputerek" = "INTEL" ]; then
		pliki="/opt/NeteXt73/kernel-premium"
		ikona="linux-premium.png"
		menu_dodatkowe=""
	elif [ "$1" = "premium" ] && [ "$komputerek" = "AMD" ]; then
		pliki="/opt/NeteXt73/kernel-premium-amd"
		ikona="linux-premium.png"
		menu_dodatkowe=""
	fi
	if [ -e /etc/netext73/kernel_premium ] && [ -e /etc/netext73/vsftpd/vsftpd ] && [ -e /etc/netext73/has* ]; then
		menu_dodatkowe="--button="$TEXT_LOKALNE:3" --button="$TEXT_NAGLOWKI:2" --button="$TEXT_PPA:4""
	elif [ -e /etc/netext73/kernel_premium ];then
		menu_dodatkowe="--button="$TEXT_LOKALNE:3" --button="$TEXT_NAGLOWKI:2""
	fi
	
	if [ "$kern" = "" ]; then
		if [ "$komputerek_intel" != "" ]; then
			yad --center --text="$TEXT_PPA_1 <span color=\"$kolor_textu\"><b>$komputerek_intel</b></span>" --icons --class="NeteXt'73" --name="NeteXt'73" --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/$ikona" \
			 --image-on-top --item-width="$((220*$skala))" --read-dir="$pliki" --width="$(($szer*$skala))" --height="$wysokosc" \
			--title="$nazwa_skryptu " $menu_dodatkowe --button="$TEXT_ZAMKNIJ:1" --single-click --timeout=15
			klawisz=$?
		else
			yad --center --icons --class="NeteXt'73" --name="NeteXt'73" --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/$ikona" \
			 --image-on-top --item-width="$((220*$skala))" --read-dir="$pliki" --width="$(($szer*$skala))" --height="$wysokosc" \
			--title="$nazwa_skryptu " $menu_dodatkowe --button="$TEXT_ZAMKNIJ:1" --single-click --timeout=15
			klawisz=$?		
		fi
	fi
fi

if [ "$klawisz" = "4" ]; then
	kern="$TEXT_PPA"
elif [ "$klawisz" = "2" ]; then
	kern="$TEXT_NAGLOWKI"
elif [ "$klawisz" = "3" ]; then
	kern="$TEXT_LOKALNE"
fi

rodzaj=$(echo $kern | cut -d " " -f 1 | awk '{print tolower($0)}')
#lokalne
if [ "$kern" = "$TEXT_LOKALNE" ]; then
	a=$(yad --center --on-top --file-selection --filename="$download/" --title="$(echo $TEXT_DEB1 | sed 's/headers/headers ext73 /' | sed 's/image/image ext73 /')" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --width=$((750*$skala)) --height=$((450*$skala)) --button="gtk-ok:0" --button="$TEXT_POWROT:1")
	if [ $? = 0 ]; then
		if [ "$(echo $a | grep 'linux-image' | grep 'ext' | grep '.deb')" != "" ]; then
			cd $(echo $a | sed -e 's/linux.*//g');     b=$(echo $a | sed -e 's/linux-image/linux-headers/g')
			echo "tak" > /tmp/netext73/ok.txt
		elif [ "$(echo $a | grep 'linux-headers' | grep 'ext' | grep '.deb')" != "" ]; then
			cd $(echo $a | sed -e 's/linux.*//g');     b=$(echo $a | sed -e 's/linux-headers/linux-image/g')
			echo "tak" > /tmp/netext73/ok.txt
		else
			yad --center --error --title="$nazwa_skryptu" --text="$(echo $TEXT_DEB1 | sed 's/:/!/' | sed 's/headers/headers ext73 /' | sed 's/image/image ext73 /')" --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0"  --timeout=15 
			echo "nie" > /tmp/netext73/ok.txt
		fi
		if [ "$(cat /tmp/netext73/ok.txt)" = "tak" ]; then
			rm /tmp/netext73/kernel -fr; 	mkdir /tmp/netext73/kernel
			cd /tmp/netext73/kernel; 	cp $a $b /tmp/netext73/kernel/
			naglowek > instaluj.sh
			#sprawdz_gcc >> instaluj.sh
			instaluj_kernel >> instaluj.sh
			instalacja2
			#zgoda na wysyłanie raportów
			zgada_na_raport
			cd /tmp/netext73; rm -rf kernel
			restart
		fi
	fi
#tylko nagłówki
elif [ "$kern" = "$TEXT_NAGLOWKI" ]; then
	a=$(yad --center --on-top --file-selection --filename="$download/" --title="$(echo $TEXT_DEB1 | sed 's/lub linux-image//' | sed 's/headers/headers ext73/')" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --width=$((750*$skala)) --height=$((450*$skala)) --button="gtk-ok:0" --button="$TEXT_POWROT:1")
	if [ $? = 0 ]; then
	if [ "$(echo $a | grep 'linux-image' | grep 'ext' | grep '.deb')" != "" ]; then
		cd $(echo $a | sed -e 's/linux.*//g');	b=$(echo $a | sed -e 's/linux-image/linux-headers/g')
		rm /tmp/netext73/kernel -fr; 	mkdir /tmp/netext73/kernel
		cd /tmp/netext73/kernel;    	cp $b /tmp/netext73/kernel/
		xterm -T instalator -e bash -c "/usr/bin/yes | sudo dpkg -i linux-headers*"
		restart
	elif [ "$(echo $a | grep 'linux-headers' | grep 'ext' | grep '.deb')" != "" ]; then
		cd $(echo $a | sed -e 's/linux.*//g')
		rm /tmp/netext73/kernel -fr; 	mkdir /tmp/netext73/kernel
		cd /tmp/netext73/kernel;		cp $a /tmp/netext73/kernel/
		xterm -T instalator -e bash -c "/usr/bin/yes | sudo dpkg -i linux-headers*"
		restart
	else
		yad --center --error --title="$nazwa_skryptu"  --text="$(echo $TEXT_DEB1 | sed -e 's/:/!/' -e 's/lub linux-image//' -e 's/headers/headers ext73 /')" --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0"  --timeout=15
	fi
	fi
#kernele PPA
elif [ "$kern" = "$TEXT_PPA" ]; then
	cd /tmp/netext73; rm *.html -f
	strona="http://kernel.ubuntu.com/~kernel-ppa/mainline/"
	WERSJA_DISTRO=$(yad --center --on-top --title="$nazwa_skryptu" --width=$((420*$skala)) --window-icon="/opt/NeteXt73/ikony/linux.png" --text="$TEXT_PPA_1 <span color=\"$kolor_textu\">$WERSJA_UBUNTU</span>" --form --field="$TEXT_RODZAJ_SYSTEMU:CB"  "$wersje_ubu" --button="gtk-ok:0" --button="$TEXT_POWROT:1")
	klawisz=$?; export WERSJA_DISTRO=$(echo $WERSJA_DISTRO | cut -d "|" -f 1)
	if [ "$klawisz" = 0 ];then
		wget $strona  2>&1 | pobieranie 
		a=$(yad --center --height=$((630*$skala)) --width=$((410*$skala)) --button="gtk-ok:0" --button="$TEXT_POWROT:1" --window-icon="/opt/NeteXt73/ikony/linux.png" --list $(grep 'href=' ./index.html | cut -d '"' -f 8 | grep $WERSJA_DISTRO | sed -e "s/-$WERSJA_DISTRO//g" -e 's/v//g' -e 's/\(.*\)./\1/' | grep -v -E "3.8.13.28" | sort -r  | awk 'ORS=NR%3?"\t\t\t":"\n"') --column="" --text="$TEXT_LISTA_KERNELI <b><span color=\"$kolor_textu\">$WERSJA_DISTRO</span></b> \n\n$TEXT_ZAZNACZ_KERNEL" --title="Kernel instalator")
		klawisz=$?
		if [ "$klawisz" = 0 ] && [ "$a" != "" ];then
			a="v"$(echo $a | cut -d '|' -f 1)"-"$WERSJA_DISTRO
			rm index.html -f; rm $PWD/v$a-$WERSJA_DISTRO -rf
			mkdir $a; cd $a
			pobieranie_kerneli
			find $PWD -type f | grep -v -E "*.deb" | xargs rm -f
			if yad --center --question --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="$TEXT_TAK:0" --button="$TEXT_POWROT:1" --text="Kernel $a $TEXT_INSTALOWAC_KERNEL"; then
				echo $PWD > /tmp/netext73/katalog.txt
				xterm -T instalator -e bash -c "cd $(cat /tmp/netext73/katalog.txt) && /usr/bin/yes | sudo dpkg -i *.deb && rm katalog.txt -f"
				restart
			else
				echo -n "cd "$PWD" && /usr/bin/yes | sudo dpkg -i *.deb" | xclip -selection clipboard
				yad --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --text="$TEST_INSTALOWAC_KERNEL2"
				if [ "$?" = "1" ]; then
					  exit 1
				fi
			fi
		fi
	fi
#instalacja kerneli ext73
elif [ "$kern" != "" ] && [ "$blad" != "1" ]; then
	if [ "$rodzaj" != "" ]; then
		lista_kerneli
		if [ "$klawisz" = "0" ] && [ "$blad" != "1" ] ; then
			if [ "$(echo $a1)" = "-" ]; then
				rm ./index.html -f; rm $a -rf
				mkdir $a; cd $a
				#wywołanie funkcji pobierania odpowiednich wersji kerneli
				if [ "$premium" = "tak" ] && [ "$kernel_premium" != "tak" ]; then
					str=""
					strona=$(yad --center  --entry --width=$((610*$skala)) --window-icon="/opt/NeteXt73/ikony/linux.png" --title="$nazwa_skryptu" --text="$TEXT_STRONA1" --entry-text="$str" --button="gtk-ok:0" --button="$TEXT_POWROT:1")
					klawisz=$?
					if [ "$klawisz" = "1" ] || [ "$(echo $strona | grep '@'  | grep '@')" = "" ]; then
						exit 1
					elif [ "$klawisz" = "0" ]; then
						echo $strona > /etc/netext73/kernel_premium
						strona="$adres_glowny/kernele_premium$katalog2/"
						export US1=$(cat /etc/netext73/kernel_premium | cut -d '@' -f 1) 
						export PASS1=$(cat /etc/netext73/kernel_premium | cut -d '@' -f 3)
						export kernel_premium="tak"
						pobieranie_kerneli
					fi
				else
					pobieranie_kerneli
				fi
				if [ "$(grep $(md5sum linux-image*) $sumy_kontrolne)" != "" ] && [ "$(grep $(md5sum linux-headers*) $sumy_kontrolne)" != "" ]; then
					echo "nie" > /tmp/netext73/ok.txt
					if [ -e linux-headers* ] && [ -e linux-image* ]; then
						naglowek > instaluj.sh
						instaluj_kernel >> instaluj.sh
						instalacja2
						#zgoda na wysyłanie raportów
						zgoda_na_raport
						#wywalenie plików po instalacji
						wywal_pobrane_pliki_kernela
						wymagana_instalacja_nv
						restart kernel
					else
						dymek  -i $warning1 "$TEXT_UWAGA" "$TEXT_INSTALOWAC_KERNEL6"
						blad=1
					fi
				else
					yad --center --error --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/error.png" --image="/opt/NeteXt73/ikony/error.png" --button="gtk-ok:0" --title="$nazwa_skryptu"  --text="$TEXT_SUMA_KONTROLNA"
				fi
			else
				yad --center --info --title="$nazwa_skryptu"  --window-icon="/opt/NeteXt73/ikony/info.png" --image="/opt/NeteXt73/ikony/info.png" --button="gtk-ok:0" --title="$nazwa_skryptu"  --text="$TEXT_INSTALOWAC_KERNEL7"
			fi
		fi
	fi
fi
