#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury

#########################################################################################################################################################################
#Logi systemowe

cd /tmp/netext73
please_wait

if [ -e losowa ];then
	export losowa=$(cat losowa)
	(( losowa++ ))
	echo $losowa > losowa
    
else
	export losowa=1; echo $losowa > losowa
fi

#informacje o systemie
#GCC
if [ "$(dmesg | grep gcc)" != "" ]; then
	echo -e "<span color=\"$kolor_textu\"><b>$TEXT_LOGI0</b></span>\n$(dmesg | grep gcc  | sed 's/.*Linux/Linux/g' )" > system$losowa.log	
else
	echo -e "<span color=\"$kolor_textu\"><b>$TEXT_LOGI0</b></span>\n$(uname -a  | sed 's/.*Linux/Linux/g' )" > system$losowa.log	
fi
#procesor i wifi
echo -e "<span color=\"$kolor_textu\"><b>$TEXT_LOGI2</b></span>" >> system$losowa.log
echo -e "$(grep 'model name' /proc/cpuinfo | head -n1 | sed -e 's/model name'[[:space:]]:'//g' | sed -e 's/ //')" >>system$losowa.log
if [ "$(lspci | grep "Network controller:" |sed -e 's/'.*:'//g' -e 's/Network Connection//g' | head -n1 | sed -e 's/ //')" = "" ]; then
	wifi="no wifi"
else
	wifi="$(lspci | grep "Network controller:" |sed -e 's/'.*:'//g' -e 's/Network Connection//g' | head -n1 | sed -e 's/ //')"
fi
echo -e "$wifi" >> system$losowa.log
#scheduler
if [ "$(grep none /sys/block/sd*/queue/scheduler)" != "" ]; then
	echo -e "scheduler I/O :\nblk-mq" >> system$losowa.log 
else
	echo -e "scheduler I/O :\n$(cat /sys/block/sd*/queue/scheduler)"  >> system$losowa.log
fi
#system
echo -e "<span color=\"$kolor_textu\"><b>SYSTEM:</b></span> $(lsb_release -i | awk '{print $3}') $NR_WERSJA_UBUNTU $WERSJA_UBUNTU $bit" >> system$losowa.log
echo -e "<span color=\"$kolor_textu\"><b>$TEXT_LOGI6</b></span>" >> system$losowa.log
#microcode intel
if [ "$(dpkg -l intel-microcode | grep "ii" | awk '{print $1}'| head -n1)" = "ii" ];  then
	echo "microcode Intel - <b>ON</b>" >> system$losowa.log
else
	echo "microcode Intel- <b>OFF</b>" >> system$losowa.log
fi
#microcode amd
if [ -e /lib/firmware/amd-ucode/microcode_amd.bin ];  then
	echo "microcode AMD - <b>ON</b>" >> system$losowa.log
else
	echo "microcode AMD - <b>OFF</b>" >> system$losowa.log
fi
#apm status
if [ "$stan_apm" != "-" ]; then
	echo -e "$TEXT_SKRYPT APM - <b>ON</b>" >> system$losowa.log
else
	echo -e "$TEXT_SKRYPT APM - <b>$TEXT_LOGI7</b>" >> system$losowa.log
fi

#sprawdzanie czy jest nvidia_optimus
if [ "$(lspci | grep -i VGA | grep -i Intel)" != "" ] && [ "$(lspci | grep -i GeForce | grep -i NVIDIA)" != "" ];then
	if [ "$(cat /proc/acpi/bbswitch 0000:03:00.0 | grep -i on)" != "" ]; then 
		echo -e "Nvidia Optimus - <b>ON</b>" >> system$losowa.log 
	else 
		echo -e "Nvidia Optimus - <b>OFF</b>" >> system$losowa.log 
	fi
fi

if [ -e $wersja_apm ]; then
	echo "$TEXT_LOGI8 APM: <b>$(ls -al /etc/default/grub | cut -d " " -f 3)</b>" >> system$losowa.log
fi
if [ -e /lib/firmware/amd-ucode/microcode_amd.bin ]; then
	echo "$TEXT_LOGI8 microcode_amd.bin: <b>$(ls -al /lib/firmware/amd-ucode/microcode_amd.bin | cut -d " " -f 3)</b>" >> system$losowa.log
fi
if [ -e /lib/firmware/amd-ucode/microcode_amd_fam15h.bin ]; then
	echo "$TEXT_LOGI8 microcode_amd_fam15h.bin: <b>$(ls -al /lib/firmware/amd-ucode/microcode_amd_fam15h.bin | cut -d " " -f 3)</b>" >> system$losowa.log
fi
echo "$TEXT_LOGI8 GRUB: <b>$(ls -al /etc/default/grub | cut -d " " -f 3)</b>" >> system$losowa.log
echo -e "<span color=\"$kolor_textu\"><b>$TEXT_LOGI9</b></span>" >> system$losowa.log
grep "GRUB_CMDLINE_LINUX=" /etc/default/grub >> system$losowa.log
echo -e "<span color=\"$kolor_textu\"><b>$TEXT_LOGI10</b></span>" >> system$losowa.log
echo "GCC - $(gcc --version | head -n 1)" >> system$losowa.log
echo "Powertop - $(dpkg -l | grep powertop | awk '{print $3}' | head -n 1)" >> system$losowa.log
mv system$losowa.log zakladka1.log

#OpenGl
echo -e "OpenGL" > opengl$losowa.log
echo -e "##############################################################################################" >> opengl$losowa.log
glxinfo | grep OpenGL | sed 's/OpenGL ext.*//g' | sed 's/OpenGL core profile extensions://g' | sed '/^[ \t]*$/ d' >> opengl$losowa.log
if [ "$(lspci | grep 3D)" != "" ]; then
	echo -e "Optimus OpenGL" >> opengl$losowa.log
	echo -e "##############################################################################################" >> opengl$losowa.log
	primusrun glxinfo | grep OpenGL  >> opengl$losowa.log
fi

#zakładka2
echo -e "NeteXt73 i kernel" > system$losowa.log  
echo -e "##############################################################################################" >> system$losowa.log
echo -e "\n$TEXT_LOGI12" >> system$losowa.log
echo -e "$(lsb_release -a)" >> system$losowa.log
echo -e "$(uname -a)" >> system$losowa.log
echo -e "\n$nazwa_skryptu"  >> system$losowa.log
echo -e "\n$TEXT_LOGI1\n$(dpkg -l | grep 'linux-image*'| grep -v -E 'linux-image-extra*|linux-image-generic' | sed -e 's/linux-image-//g' | awk '{print $2}'| sort -r | column -n)" >> system$losowa.log
echo -e "\n\nKonfiguracja netext73" >> system$losowa.log
echo -e "##############################################################################################" >> system$losowa.log
#katalogi
ls -la ~/.netext73 | grep drwxrwxr-x | sed '1s/.*//' >> system$losowa.log
#pliki
ls -la ~/.netext73 | grep rw-rw >> system$losowa.log
echo -e "\n\narchiwum_deb" >> system$losowa.log
echo -e "##############################################################################################" >> system$losowa.log
cat ~/.netext73/archiwum_deb >> system$losowa.log
echo -e "\n\ninstalator_kerneli" >> system$losowa.log
echo -e "##############################################################################################" >> system$losowa.log
cat ~/.netext73/instalator_kerneli >> system$losowa.log
echo -e "\n\njezyk" >> system$losowa.log
echo -e "##############################################################################################" >> system$losowa.log
cat ~/.netext73/jezyk >> system$losowa.log
echo -e "\n\nkernel_automat " >> system$losowa.log
echo -e "##############################################################################################" >> system$losowa.log
cat ~/.netext73/kernel_automat >> system$losowa.log
echo -e "\n\nroot_mode " >> system$losowa.log
echo -e "##############################################################################################" >> system$losowa.log
cat ~/.netext73/root_mode >> system$losowa.log
echo -e "\n\nzswap " >> system$losowa.log
echo -e "##############################################################################################" >> system$losowa.log
dmesg | grep zswap: >> system$losowa.log
echo -e "\n\nkonflikty " >> system$losowa.log
echo -e "##############################################################################################" >> system$losowa.log
dpkg -l | awk '{print $2}' | grep laptop-mode-tools -x >> system$losowa.log    
dpkg -l | awk '{print $2}' | grep tlp -x >> system$losowa.log    
echo -e "\n\nstan tmp " >> system$losowa.log
echo -e "##############################################################################################" >> system$losowa.log
ls -la /tmp/netext73 | grep -v drwxr | sed '1s/.*//' >> system$losowa.log
echo -e "\n\nsumy kontrolne " >> system$losowa.log
echo -e "##############################################################################################" >> system$losowa.log
cat /tmp/netext73/sumy/* >> system$losowa.log

echo -e "\n\nmounted-proc.conf " >> system$losowa.log
echo -e "##############################################################################################" >> system$losowa.log
cat /etc/init/mounted-proc.conf >> system$losowa.log
echo -e "\n\nureadahead.conf  " >> system$losowa.log
echo -e "##############################################################################################" >> system$losowa.log
cat /etc/init/ureadahead.conf >> system$losowa.log
echo -e "\n\nreadahead  " >> system$losowa.log
echo -e "##############################################################################################" >> system$losowa.log
cat /usr/lib/pm-utils/power.d/readahead >> system$losowa.log

echo -e "microcode  " >> apmsystem$losowa.log
echo -e "##############################################################################################" >> apmsystem$losowa.log
if [ "$(dpkg -l intel-microcode | grep "ii" | awk '{print $1}'| head -n1)" = "ii" ];  then
      echo "microcode Intel - ON" >> apmsystem$losowa.log
else
      echo "microcode Intel- OFF" >> apmsystem$losowa.log
fi
if [ -e /lib/firmware/amd-ucode/microcode_amd.bin ];  then
      echo "microcode AMD - ON" >> apmsystem$losowa.log
else
      echo "microcode AMD - OFF" >> apmsystem$losowa.log
fi
dpkg -l | grep linux-firmware | awk '{print $2" "$3}' | head -n 1 | sed 's/~.*//'  >> apmsystem$losowa.log

echo -e "\n\nwersja APM  " >> apmsystem$losowa.log
echo -e "##############################################################################################" >> apmsystem$losowa.log
ls $katalog_apm | cut -d "_" -f 7 | head -n 1 >> apmsystem$losowa.log
echo -e "\napm_status " >> apmsystem$losowa.log

ls /usr/lib/pm-utils/power.d/ -la | grep rwxr | grep -v drwxr-xr-x >> apmsystem$losowa.log
ls /etc/pm/power.d/ -la | grep -v drwxr-xr-x | sed '1s/.*//' >>  apmsystem$losowa.log
echo -e "\nls /usr/lib/pm-utils/power.d/ -la" >> apmsystem$losowa.log
ls /usr/lib/pm-utils/power.d/ -la | grep -v drwxr-xr-x | sed '1s/.*//' >> apmsystem$losowa.log
echo -e "\nls /etc/apm/event.d/ -la" >> apmsystem$losowa.log
ls -la /etc/apm/event.d/ | grep -v drwxr-xr-x | sed '1s/.*//' >> apmsystem$losowa.log
if [ "$apmik" = "nowy" ]; then
	cat /etc/systemd/system/hibernate.target.wants/apm_ext73-resume.service >> apmsystem$losowa.log
	cat /etc/systemd/system/hybrid-sleep.target.wants/apm_ext73-resume.service >> apmsystem$losowa.log
	cat /etc/systemd/system/suspend.target.wants/apm_ext73-resume.service >> apmsystem$losowa.log
	cat /etc/udev/rules.d/50-udev-apm.rules  >> apmsystem$losowa.log	
fi


echo -e "##############################################################################################" >> apmsystem$losowa.log
cat ~/.netext73/apm_status | tr ' ' '\t' >> apmsystem$losowa.log
echo -e "\n\nscheduler  " >> apmsystem$losowa.log
echo -e "##############################################################################################" >> apmsystem$losowa.log
if [ "$(grep none /sys/block/sd*/queue/scheduler)" != "" ]; then
	echo -e "scheduler I/O :\nblk-mq" >> apmsystem$losowa.log 
else
	echo -e "scheduler I/O :\n$(cat /sys/block/sd*/queue/scheduler)"  >> apmsystem$losowa.log
fi

echo -e "lsmod" >> lsmodsystem$losowa.log
echo -e "##############################################################################################" >> lsmodsystem$losowa.log
lsmod >> lsmodsystem$losowa.log
echo -e "lspci" >> lspcisystem$losowa.log
echo -e "##############################################################################################" >> lspcisystem$losowa.log
lspci >> lspcisystem$losowa.log
echo -e "lsusb" >> lsusbsystem$losowa.log
echo -e "##############################################################################################" >> lsusbsystem$losowa.log
lsusb >> lsusbsystem$losowa.log
echo -e "qlxinfo" >> glxinfo$losowa.log
echo -e "##############################################################################################" >> glxinfo$losowa.log
glxinfo >> glxinfo$losowa.log
if [ "$(lspci | grep 3D)" != "" ]; then
	echo -e "##############################################################################################" >> glxinfo$losowa.log
	primusrun glxinfo | grep OpenGL  >> glxinfo$losowa.log
fi

sed -i 's/<\/span>//g' system$losowa.log
sed -i 's/<span.*">//g' system$losowa.log
sed -i 's/<\/b>//g' system$losowa.log
sed -i 's/<b>//g' system$losowa.log
mv system$losowa.log netext.log

echo -e "dmesg".log > dmesg.log
echo -e "##############################################################################################" >> dmesg.log
dmesg >> dmesg.log

echo -e "firewall.log" > firewall.log
echo -e "##############################################################################################" >> firewall.log
sudo ufw status verbose >> firewall.log

echo -e "dmidecode.log" > dmidecode.log
echo -e "##############################################################################################" >> dmidecode.log
for i in $(seq 1 42); do sudo dmidecode --type $i >> dmidecode.log; done

echo -e "kern.log" > kern.log
echo -e "##############################################################################################" >> kern.log
sudo tac /var/log/kern.log | sed -n 1,1000p >> kern.log

#przygotowanie informacji o zainstalowanych plikach
rm /tmp/netext73/sumy/pliki.txt -f
dpkg -l | grep -wE "linux-headers|nvidia|fglrx" | grep ii > /tmp/netext73/sumy/pakiety.txt
cat /tmp/netext73/sumy/pakiety.txt | grep linux-headers		| sed 's/-headers//g' | awk '{print $2}'  	> /tmp/netext73/sumy/lista.txt
cat /tmp/netext73/sumy/pakiety.txt | grep nvidia 	  	| awk '{print $2"_"$3}' >> /tmp/netext73/sumy/lista.txt
cat /tmp/netext73/sumy/pakiety.txt | awk '{print $2"_"$3}' 	| sed 's/.://g' | grep fglrx_ >> /tmp/netext73/sumy/lista.txt
cat /tmp/netext73/sumy/sumy_kontrolne.txt | awk '{print $2}' 	| grep -v -E 'image|amdcccle' -v | sed 's/_amd64.deb//g' | sed 's/.tar.xz//g' | sed 's/-headers//g' > /tmp/netext73/sumy/wydane.txt

for i in $(cat /tmp/netext73/sumy/wydane.txt); do 
	if [ "$(echo $i | grep fglrx )" = "" ];then
		if [ "$(cat /tmp/netext73/sumy/lista.txt | grep -x $i)" = "" ]; then
			echo "FALSE $i" >> /tmp/netext73/sumy/pliki.txt
		else
			echo "TRUE $i" >> /tmp/netext73/sumy/pliki.txt
		fi
	else
		if [ "$(cat /tmp/netext73/sumy/lista.txt | grep -x $(echo $i | sed 's/.*_fglrx/fglrx/g'))" = "" ]; then
			echo "FALSE $i" >> /tmp/netext73/sumy/pliki.txt
		else
			echo "TRUE $i" >> /tmp/netext73/sumy/pliki.txt
		fi
	fi
done
cat /tmp/netext73/sumy/pliki.txt | sort -r | uniq > /tmp/netext73/sumy/pakiety.txt
rm -f /tmp/netext73/sumy/pliki.txt /tmp/netext73/sumy/wydane.txt /tmp/netext73/sumy/lista.txt



#system logi
please_wait kill

if [ -e ~/.netext73/wysylkalogow ]; then
	s1="$(cat ~/.netext73/wysylkalogow | sed -n 1p)"
	s2="$(cat ~/.netext73/wysylkalogow | sed -n 2p)"
	s3="$(cat ~/.netext73/wysylkalogow | sed -n 3p)"
	s4="$(cat ~/.netext73/wysylkalogow | sed -n 4p)"
	s5="$(cat ~/.netext73/wysylkalogow | sed -n 5p)"
	s6="$(cat ~/.netext73/wysylkalogow | sed -n 6p)"
	s7="$(cat ~/.netext73/wysylkalogow | sed -n 7p)"
	s8="$(cat ~/.netext73/wysylkalogow | sed -n 8p)"
	s9="$(cat ~/.netext73/wysylkalogow | sed -n 9p)"
	s10="$(cat ~/.netext73/wysylkalogow | sed -n 10p)"
else
	s1="TRUE"
	s2="TRUE"
	s3="TRUE"
	s4="TRUE"
	s5="FALSE"
	s6="TRUE"
	s7="TRUE"
	s8="TRUE"
	s9="TRUE"
	s10="TRUE"
fi

KEY="$(echo $RANDOM)"
#zmienne losowe
res0=$(mktemp --tmpdir=/tmp/netext73 netext73_0.XXXXXXXX)
res1=$(mktemp --tmpdir=/tmp/netext73 netext73_1.XXXXXXXX)
res2=$(mktemp --tmpdir=/tmp/netext73 netext73_2.XXXXXXXX)
res3=$(mktemp --tmpdir=/tmp/netext73 netext73_3.XXXXXXXX)
res4=$(mktemp --tmpdir=/tmp/netext73 netext73_4.XXXXXXXX)
res5=$(mktemp --tmpdir=/tmp/netext73 netext73_5.XXXXXXXX)
res6=$(mktemp --tmpdir=/tmp/netext73 netext73_6.XXXXXXXX)
res7=$(mktemp --tmpdir=/tmp/netext73 netext73_7.XXXXXXXX)
res8=$(mktemp --tmpdir=/tmp/netext73 netext73_8.XXXXXXXX)
res9=$(mktemp --tmpdir=/tmp/netext73 netext73_9.XXXXXXXX)
res10=$(mktemp --tmpdir=/tmp/netext73 netext73_10.XXXXXXXX)
res11=$(mktemp --tmpdir=/tmp/netext73 netext73_11.XXXXXXXX)
res12=$(mktemp --tmpdir=/tmp/netext73 netext73_12.XXXXXXXX)

#zakładki
yad --plug=$KEY --tabnum=1 --text="$(cat zakladka1.log)"	&> $res0 &
yad --plug=$KEY --tabnum=2 --text-info --filename="netext.log"	&> $res1 &
yad --plug=$KEY --tabnum=3 --text-info --filename="opengl$losowa.log"	&> $res2 &
yad --plug=$KEY --tabnum=4 --text-info --filename="dmesg.log"	&> $res3 &
yad --plug=$KEY --tabnum=5 --text-info --filename="kern.log"	&> $res4 &
yad --plug=$KEY --tabnum=6 --text-info --filename="firewall.log" 	&> $res5 &
yad --plug=$KEY --tabnum=7 --text-info --filename="dmidecode.log" 	&> $res6 &
yad --plug=$KEY --tabnum=8 --text-info --filename="glxinfo$losowa.log"	&> $res7 &
yad --plug=$KEY --tabnum=9 --text-info --filename="apmsystem$losowa.log"	&> $res8 &
yad --plug=$KEY --tabnum=10 --text-info --filename="lsmodsystem$losowa.log"	&> $res9 &
yad --plug=$KEY --tabnum=11 --text-info --filename="lspcisystem$losowa.log"	&> $res10 &
yad --plug=$KEY --tabnum=12 --text-info --filename="lsusbsystem$losowa.log"	&> $res11 &
yad --plug=$KEY --tabnum=13 --text="<span color=\"$kolor_textu\"><b>$TEXT_ZAZNACZ_LOGI</b></span>" --form --columns=4 --field="netext.log:CHK" --field="opengl.log:CHK" --field="dmesg.log:CHK" --field="kern.log:CHK" --field="firewall.log:CHK" --field="glxinfo.log:CHK" --field="apm-microcode.log:CHK" --field="lsmod.log:CHK" --field="lspci.log:CHK" --field="lsusb.log:CHK" $s1 $s2 $s3 $s4 $s5 $s6 $s7 $s8 $s9	$s10 &> $res12 &
yad --notebook --key=$KEY --center --title="$nazwa_skryptu1 " --tab-pos="left" \
--tab="main" --tab="netext" --tab="OpenGl" --tab="dmesg" --tab="kern" --tab="firewall" --tab="dmidecode" \
--tab="glxinfo" --tab="APM-microcode" --tab="lsmod" --tab="lspci" --tab="lsusb" --tab="$TEXT_ZAZNACZ_LOGI_OPCJE" \
--window-icon="/opt/NeteXt73/ikony/logi.png"  --width=$((860*$skala)) --height=$((500*$skala)) --on-top --button="$TEXT_PASTEBIN:0" --button="$TEXT_ZAMKNIJ:1" --button="$TEXT_LISTAPAKIETOW:2" --button="LOG2:3"
klawisz=$?
if [ "$klawisz" = "2" ]; then
	KEY="$(echo $RANDOM)"
	res4=$(mktemp --tmpdir=/tmp/netext73 netext73_4.XXXXXXXX)
	res5=$(mktemp --tmpdir=/tmp/netext73 netext73_5.XXXXXXXX)
	res6=$(mktemp --tmpdir=/tmp/netext73 netext73_6.XXXXXXXX)
	res7=$(mktemp --tmpdir=/tmp/netext73 netext73_7.XXXXXXXX)
	res8=$(mktemp --tmpdir=/tmp/netext73 netext73_8.XXXXXXXX)
	res9=$(mktemp --tmpdir=/tmp/netext73 netext73_9.XXXXXXXX)
	res10=$(mktemp --tmpdir=/tmp/netext73 netext73_10.XXXXXXXX)
	res11=$(mktemp --tmpdir=/tmp/netext73 netext73_11.XXXXXXXX)
	res12=$(mktemp --tmpdir=/tmp/netext73 netext73_12.XXXXXXXX)
	res13=$(mktemp --tmpdir=/tmp/netext73 netext73_13.XXXXXXXX)
	res14=$(mktemp --tmpdir=/tmp/netext73 netext73_14.XXXXXXXX)
	res15=$(mktemp --tmpdir=/tmp/netext73 netext73_15.XXXXXXXX)
	
	yad --plug=$KEY --tabnum=1 --checklist --list $(cat /tmp/netext73/sumy/pakiety.txt  | grep fglrx_ ) --column "$TEXT_ZNITY1" --column "catalist" &> $res4 &
	yad --plug=$KEY --tabnum=2 --checklist --list $(cat /tmp/netext73/sumy/pakiety.txt  | grep nvidia | grep -v -E "nvidia-settings.*|libnvidia-") --column "$TEXT_ZNITY1" --column "nvidia" &> $res5 &
	yad --plug=$KEY --tabnum=3 --checklist --list $(cat /tmp/netext73/sumy/pakiety.txt  | grep k8 	  ) --column "$TEXT_ZNITY1" --column "kernel k8" &> $res6 &
	yad --plug=$KEY --tabnum=4 --checklist --list $(cat /tmp/netext73/sumy/pakiety.txt  | grep atom	  ) --column "$TEXT_ZNITY1" --column "kernel atom" &> $res7 &
	yad --plug=$KEY --tabnum=5 --checklist --list $(cat /tmp/netext73/sumy/pakiety.txt  | grep -E "sandy") --column "$TEXT_ZNITY1" --column "kernel sandy" &> $res8 &
	yad --plug=$KEY --tabnum=6 --checklist --list $(cat /tmp/netext73/sumy/pakiety.txt  | grep -E "ivy") --column "$TEXT_ZNITY1" --column "kernel ivy" &> $res9 &
	yad --plug=$KEY --tabnum=7 --checklist --list $(cat /tmp/netext73/sumy/pakiety.txt  | grep -E "haswell" ) --column "$TEXT_ZNITY1" --column "kernel haswell" &> $res10 &
	yad --plug=$KEY --tabnum=8 --checklist --list $(cat /tmp/netext73/sumy/pakiety.txt  | grep -E "broadwell") --column "$TEXT_ZNITY1" --column "kernel broadwell" &> $res11 &
	yad --plug=$KEY --tabnum=9 --checklist --list $(cat /tmp/netext73/sumy/pakiety.txt  | grep -E "skylake") --column "$TEXT_ZNITY1" --column "kernel skylake" &> $res12 &
	yad --plug=$KEY --tabnum=10 --checklist --list $(cat /tmp/netext73/sumy/pakiety.txt | grep -E "brazos"  ) --column "$TEXT_ZNITY1" --column "kernel brazos" &> $res13 &
	yad --plug=$KEY --tabnum=11 --checklist --list $(cat /tmp/netext73/sumy/pakiety.txt | grep -E "bulldozer" ) --column "$TEXT_ZNITY1" --column "kernel bulldozer" &> $res14 &
	yad --plug=$KEY --tabnum=12 --checklist --list $(cat /tmp/netext73/sumy/pakiety.txt | grep -E "piledriver" ) --column "$TEXT_ZNITY1" --column "kernel piledriver" &> $res15 &

	yad --notebook --key=$KEY --tab-pos="left" --center --title="$nazwa_skryptu1 " \
      --tab="catalyst" --tab="nvidia" --tab="k8" --tab="atom" \
      --tab="sandy" --tab="ivy" --tab="haswell" --tab="broadwell" --tab="skylake" \
      --tab="brazos" --tab="buldozer" --tab="piledriver" \
      --window-icon="/opt/NeteXt73/ikony/netext.png" --on-top --width=$((860*$skala)) --height=$((390*$skala)) --button="$TEXT_ZAMKNIJ:1"

      rm /tmp/netext73/sumy/pliki.txt $res4 $res5 $res6 $res7 $res8 $res9 $res10 $res11 $res12 $res13 $res14 $res15 -f
elif [ "$klawisz" = "3" ]; then

	petla_duza="tak"
	while [ $petla_duza = "tak" ]; do
		a=$(yad --center --height=$((540*$skala)) --width=$((440*$skala)) --window-icon="/opt/NeteXt73/ikony/logi.png" --title="$nazwa_skryptu" --text="$TEXT_LOGI10" --column="DATA" --list $(ls ~/.netext73/logi/*.log | sed 's/.*instal...._//g' | sort | uniq) --button="$TEXT_USUN_WYNIK:2" --button="$TEXT_ZAMKNIJ:1"  --button="gtk-ok:0")
		klawisz=$?
		if [ "$klawisz" = "0" ]; then
			wynik=$(echo $a | cut -d '|' -f 1)

			KEY="$(echo $RANDOM)"

			#zmienne losowe
			res0=$(mktemp --tmpdir=/tmp/netext73 netext73_0.XXXXXXXX)
			res1=$(mktemp --tmpdir=/tmp/netext73 netext73_1.XXXXXXXX)

			yad --plug=$KEY --tabnum=1 --text-info --filename="/home/$(cat /tmp/netext73/userek)/.netext73/logi/instalujsh_$wynik" &> $res0 &
			yad --plug=$KEY --tabnum=2 --text-info --filename="/home/$(cat /tmp/netext73/userek)/.netext73/logi/instalacja_$wynik" &> $res1 &
			yad --notebook --key=$KEY --center --title="$nazwa_skryptu1 " --tab="instalujsh" --tab="instalacja" --window-icon="/opt/NeteXt73/ikony/logi.png" --image="/opt/NeteXt73/ikony/logi.png" --on-top --width=$((860*$skala)) --height=$((640*$skala)) --button="$TEXT_PASTEBIN:0" --button="$TEXT_ZAMKNIJ:1"
			klawisz=$?
			if [ "$klawisz" = "0" ]; then
				cat /home/$(cat /tmp/netext73/userek)/.netext73/logi/instalujsh_$wynik | pastebinit_netext73 "instalujsh_$wynik" && dymek -i $ikona_info1 "$TEXT_INFORMACJA" "$TEXT_PRZESLIJ_LOGI instalujsh_$wynik"
				cat /home/$(cat /tmp/netext73/userek)/.netext73/logi/instalacja_$wynik | pastebinit_netext73 "instalacja_$wynik" && dymek -i $ikona_info1 "$TEXT_INFORMACJA" "$TEXT_PRZESLIJ_LOGI instalacja_$wynik"
			fi
			rm $res0 $res1 -f
		elif [ "$klawisz" = "2" ]; then
			wynik=$(echo $a | cut -d '|' -f 1)
			rm /home/$(cat /tmp/netext73/userek)/.netext73/logi/instalujsh_$wynik /home/$(cat /tmp/netext73/userek)/.netext73/logi/instalacja_$wynik -f
		else
			opusc_petle
		fi
	done	      
elif [ "$klawisz" = "0" ]; then
	cat $res12 | cut -d "|" -f 1 > ~/.netext73/wysylkalogow
	cat $res12 | cut -d "|" -f 2 >> ~/.netext73/wysylkalogow
	cat $res12 | cut -d "|" -f 3 >> ~/.netext73/wysylkalogow
	cat $res12 | cut -d "|" -f 4 >> ~/.netext73/wysylkalogow
	cat $res12 | cut -d "|" -f 5 >> ~/.netext73/wysylkalogow
	cat $res12 | cut -d "|" -f 6 >> ~/.netext73/wysylkalogow
	cat $res12 | cut -d "|" -f 7 >> ~/.netext73/wysylkalogow
	cat $res12 | cut -d "|" -f 8 >> ~/.netext73/wysylkalogow
	cat $res12 | cut -d "|" -f 9 >> ~/.netext73/wysylkalogow
	cat $res12 | cut -d "|" -f 10 >> ~/.netext73/wysylkalogow
	      
	export userek=$(cat /tmp/netext73/userek)
	#sudo -u $userek bash << EOF
	if [ -e ~/.netext73/wysylkalogow ]; then
		if [ "$(cat  ~/.netext73/wysylkalogow | sed -n 1p)" != "FALSE" ]; then
			cat netext.log | pastebinit_netext73 netext.log && log1="netext.log"
		fi
		if [ "$(cat  ~/.netext73/wysylkalogow | sed -n 2p)" != "FALSE" ]; then
			cat opengl$losowa.log | pastebinit_netext73 opengl.log && log2="opengl.log"
		fi
		if [ "$(cat  ~/.netext73/wysylkalogow | sed -n 3p)" != "FALSE" ]; then
			cat dmesg.log | pastebinit_netext73 dmesg.log && log3="dmesg.log"
		fi
		if [ "$(cat  ~/.netext73/wysylkalogow | sed -n 4p)" != "FALSE" ]; then
			cat kern.log | pastebinit_netext73 kern.log && log4="kern.log"
		fi
		if [ "$(cat  ~/.netext73/wysylkalogow | sed -n 5p)" != "FALSE" ]; then
			cat firewall.log | pastebinit_netext73 firewall.log && log5="firewall.log"
		fi
		if [ "$(cat  ~/.netext73/wysylkalogow | sed -n 6p)" != "FALSE" ]; then
			cat glxinfo$losowa.log | pastebinit_netext73 glxinfo.log && log6="glxinfo.log"
		fi
		if [ "$(cat  ~/.netext73/wysylkalogow | sed -n 7p)" != "FALSE" ]; then
			cat apmsystem$losowa.log | pastebinit_netext73 apmsystem.log && log7="apmsystem.log"
		fi
		if [ "$(cat  ~/.netext73/wysylkalogow | sed -n 8p)" != "FALSE" ]; then
			cat lsmodsystem$losowa.log | pastebinit_netext73 lsmodsystem.log && log8="lsmodsystem.log"
		fi
		if [ "$(cat  ~/.netext73/wysylkalogow | sed -n 9p)" != "FALSE" ]; then
			cat lspcisystem$losowa.log | pastebinit_netext73 lspcisystem.log && log9="lspcisystem.log"
		fi
		if [ "$(cat  ~/.netext73/wysylkalogow | sed -n 10p)" != "FALSE" ]; then
			cat lsusbsystem$losowa.log | pastebinit_netext73 lsusbsystem.log && log10="lsusbsystem.log"
		fi
		dymek -i $ikona_info1 "$TEXT_INFORMACJA" "$TEXT_PRZESLIJ_LOGI : \n$log1\n$log2\n$log3\n$log4\n$log5\n$log6\n$log7\n$log8\n$log9\n$log10"
		
	else
		cat netext.log | pastebinit_netext73 netext.log && dymek -i $ikona_info1 "$TEXT_INFORMACJA" "$TEXT_PRZESLIJ_LOGI netext.log"
	fi
#EOF
	fi
rm -f $res0 $res1 $res2 $res3 $res4 $res5 $res6 $res7 $res8 $res9 $res10 $res11 $res12 /tmp/netext73/sumy/pakiety.txt
rm *.log losowa -f