#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury

#########################################################################################################################################################################
#monitor


#sprawdzenie sensorów jeżeli nie były włączone
if [ "$(cat /etc/modules | grep sensors-detect)" = "" ]; then
      xterm  -T "sensors" -e bash -c "/usr/bin/yes| sudo sensors-detect; sudo /etc/init.d/lm-sensors stop;sudo update-rc.d -f lm-sensors remove"
fi


cd /tmp/netext73
if [ -e ~/.netext73/monitor ]; then
	licznik="0"
	for i in $(echo system powertop HTOP saidar CPU battery); do
		licznik=$((licznik + 1 ))
		if [ "$(grep $i ~/.netext73/monitor)" != "" ]; then
			a[licznik]=TRUE
		else
			a[licznik]=FALSE
		fi
	done 
else
	a[1]=TRUE
	for i in $(seq 2 6); do
		a[$i]=FALSE
	done
fi

if [ -e /sys/class/power_supply/BAT*/uevent ]; then
	menu=$(echo "--field="system_monitor:CHK" --field="powertop:CHK" --field="HTOP:CHK" --field="saidar:CHK" --field="CPU/Memory:CHK" --field="battery:CHK" ${a[1]} ${a[2]} ${a[3]} ${a[4]} ${a[5]} ${a[6]}")
else
	menu=$(echo "--field="system_monitor:CHK" --field="powertop:CHK" --field="HTOP:CHK" --field="saidar:CHK" --field="CPU/Memory:CHK" ${a[1]} ${a[2]} ${a[3]} ${a[4]} ${a[5]}")
fi

konfiguracja=$(yad --title="$nazwa_skryptu" --window-icon="/opt/NeteXt73/ikony/monitor.png" --image="/opt/NeteXt73/ikony/monitor.png" --text="<span color=\"$kolor_textu\">$TEXT_MONITOR1</span>" --center --form --columns=3 $(echo $menu) --width="$((555*$skala))" --button="gtk-ok:0" --button="$TEXT_POWROT:1" )
klawisz=$?

if [ "$klawisz" = "0" ]; then
	rm ~/.netext73/monitor -f
	if [ "$(echo $konfiguracja | cut -d '|' -f 1 )" = "TRUE" ]; then
		echo "system" >> ~/.netext73/monitor
		xterm -T "System monitor" -e bash -c "watch -t 'uptime; echo  -n \"\nScaling governor : \"; cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;echo -n \"CPU driver       : \";cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_driver | head -n 1; echo -n \"\nCpu Core Frequency\n\";cat /proc/cpuinfo | grep MHz;echo -n \"\nMemory :\n\";free -m;echo -n \"\nSensors:\n\";sensors'" &
	fi
	if [ "$(echo $konfiguracja | cut -d '|' -f 2 )" = "TRUE" ]; then
		echo "powertop" >> ~/.netext73/monitor
		xterm -T "PowerTop" -e bash -c "sudo powertop" &
	fi
	if [ "$(echo $konfiguracja | cut -d '|' -f 3 )" = "TRUE" ]; then
		echo "HTOP" >> ~/.netext73/monitor
		xterm -T "HTop" -e bash -c "htop" &
	fi
	if [ "$(echo $konfiguracja | cut -d '|' -f 4 )" = "TRUE" ]; then
		echo "saidar" >> ~/.netext73/monitor
		xterm -T "Saidar" -e bash -c "saidar -c" &
	fi
	if [ "$(echo $konfiguracja | cut -d '|' -f 5 )" = "TRUE" ]; then
		echo "CPU" >> ~/.netext73/monitor
		procesor_monitor &
	fi
	if [ "$(echo $konfiguracja | cut -d '|' -f 6 )" = "TRUE" ] && [ -e /sys/class/power_supply/BAT*/uevent ]; then
		echo "battery" >> ~/.netext73/monitor
		stan_baterii &
	fi
fi
