#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    	   		 _   _      _      __  ___   _ _____ _____
#					    | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#					    |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   				| |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   				|_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#  __  ___ _______   ____ __  __  _   _ ___  __ _____ __  ___    ____   __ __ _____ ___ __ __ _  _
# /__\| _,\_   _\ `v' /  V  |/  \| | | |_  |/  \_   _/__\| _ \ /' _| `v' /' _/_   _| __|  V  | || |
#| \/ | v_/ | |  `. .'| \_/ | /\ | |_| |/ /| /\ || || \/ | v / `._`.`. .'`._`. | | | _|| \_/ | \/ |
# \__/|_|   |_|   !_! |_| |_|_||_|___|_|___|_||_||_| \__/|_|_\ |___/ !_! |___/ |_| |___|_| |_|\__/
#
#            __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#       ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#      / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
#     |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#      \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#procedury
source /opt/NeteXt73/procedury

#########################################################################################################################################################################

#zapobieganie dwukrotnemu uruchomieniu
if [ "$(pgrep NeteXt73 | wc -l )" -gt "3" ] || [ "$(ps -aux | grep NeteXt73 | grep Root-mode)" != '' ]; then
	dymek  -i $ikona_info1 "$TEXT_INFORMACJA" "$TEXT_NETEXT_JUZ_DZIALA"
	exit 1
fi

#pobieranie sum kontrolnych i informacji o aktualizacjach
if [ "$USER" != "root" ];then
	rm -rf /tmp/netext73/sumy/*
	mkdir -p /tmp/netext73/sumy
	wersja &
	zaleznosci &
	/opt/NeteXt73/./update start &
fi

#zapobieganie uruchomieniu programu z poziomu roota
if [ ! -e /tmp/netext73/userek ]; then
	if [ ! -e /tmp/netext73 ]; then
		mkdir -p /tmp/netext73
	fi
	echo $USER > /tmp/netext73/userek
	export userek=$(cat /tmp/netext73/userek)
	if [ "$userek" = "root" ]; then
		rm -rf /tmp/netext73
		echo -e "Please run program without sudo.\nUruchom program bez sudo."
		sudo -K
		exit 1
	else
		cd /opt/NeteXt73 && NeteXt73_root ./NeteXt73
		exit 0
	fi
fi
chown $userek:$userek ~/.netext73 -R
if [ -e ~/.netext73/kernel_premium ] && [ -e ~/.netext73/vsftpd/vsftpd ] && [ -e ~/.netext73/has* ]; then
	klawisze_aktywne="--button="vsFTPd:3" --button="$TEXT_REBOOT:2" --button="$TEXT_ZAMKNIJ:1" --single-click"
else
	klawisze_aktywne="--button="$TEXT_REBOOT:2" --button="$TEXT_ZAMKNIJ:1" --single-click"
fi
if [ "$skala" = "2" ];then
	wysokosc="720"
else
	wysokosc="680"
fi
yad --center --icons --class="NeteXt'73" --name="NeteXt'73" --window-icon="/opt/NeteXt73/ikony/NeteXt73.png" --image-on-top --item-width="$((200*$skala))" --read-dir="/opt/NeteXt73/desktopfiles" --width="$((870*$skala))" --height="$wysokosc" --title="- $nazwa_skryptu -" $klawisze_aktywne
klawisz=$?
if [ "$klawisz" = "2" ]; then
	restart
elif  [ "$klawisz" = "3" ] ; then
	chmod a+x ~/.netext73/vsftpd/vsftpd
	~/.netext73/vsftpd/./vsftpd
else
	sudo -K
	rm -rf /tmp/netext73
	exit 0
fi

