#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#start
cd /opt/NeteXt73/
source /opt/NeteXt73/procedury

if [ "$1" = "kontakty" ]; then
	KEY="$(echo $RANDOM)"

	#zmienne losowe
	res0=$(mktemp --tmpdir=/tmp/netext73 netext73_0.XXXXXXXX)
	res1=$(mktemp --tmpdir=/tmp/netext73 netext73_1.XXXXXXXX)
	res2=$(mktemp --tmpdir=/tmp/netext73 netext73_2.XXXXXXXX)
	res3=$(mktemp --tmpdir=/tmp/netext73 netext73_3.XXXXXXXX)
	res4=$(mktemp --tmpdir=/tmp/netext73 netext73_4.XXXXXXXX)
	res5=$(mktemp --tmpdir=/tmp/netext73 netext73_5.XXXXXXXX)
	
	yad --plug=$KEY --tabnum=1 --text="$TEXT_O_PROGRAMIE" &> $res0 &
	yad --plug=$KEY --tabnum=2 --icons --image-on-top --single-click --item-width=$((330*$skala)) --read-dir=/opt/NeteXt73/kontakty &> $res1 &
	yad --plug=$KEY --tabnum=3 --text-info --filename=/opt/NeteXt73/changelog &> $res2 &
	yad --plug=$KEY --tabnum=4 --text-info --filename=/opt/NeteXt73/LICENSE &> $res3 &
	yad --plug=$KEY --tabnum=5 --html --uri="http://www.netext73.pl" --browser &> $res4 &
	yad --plug=$KEY --tabnum=6 --html --uri="http://www.netext73.pl/2014/02/netext73-zgaszanie-bedow.html" --browser &> $res5 &
	yad --notebook --key=$KEY --tab-pos="left" --center --title="$nazwa_skryptu1 " --tab="$TEXT_O" --tab="$TEXT_KONTAKT_Z_AUTORAMI" --tab="$TEXT_CHANGELOG" --tab="$TEXT_LICENCJA" --tab="$TEXT_HOME_PAGE" --tab="$TEXT_BUG" \
	--window-icon="/opt/NeteXt73/ikony/netext.png" --on-top --width=$((950*$skala)) --height=$((600*$skala)) --button="$TEXT_ZAMKNIJ:1"
	klawisz=$?
	rm $res0 $res1 $res2 $res3 $res4 $res5 -f
else
	if [ "$USER" = "root" ]; then
		sudo -S $1
	else
		while ! yad --center --on-top --title="$nazwa_skryptu1 -  Root-mode" --width=$((360*$skala)) --entry --hide-text --window-icon="/opt/NeteXt73/ikony/key.png" --image="/opt/NeteXt73/ikony/key.png" --text="$TEXT_PASSWD1\n" --button="gtk-ok:0" | sudo -S $1; do
			if $(yad --center --question --title="$nazwa_skryptu1" --width=$((460*$skala)) --window-icon="/opt/NeteXt73/ikony/pytanie.png" --image="/opt/NeteXt73/ikony/pytanie.png" --button="$TEXT_TAK:0" --button="$TEXT_NIE:1" --text="$TEXT_PASSWD"); then
				exit 0
			fi
		done

	fi
fi
sudo -K

	