#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
#########################################################################################################################################################################
#procedury

source /opt/NeteXt73/procedury

#########################################################################################################################################################################
#Update

#ustawienia dla crona
if [ "$1" = "start" ]; then
	if [ ! -e /tmp/netext73/sumy ]; then
		mkdir -p /tmp/netext73/sumy
	fi
	sumy &
fi
cd /tmp/netext73

usun(){
rm *.html* -f
rm -f /tmp/netext73/*.txt
}

instalacja_gcc(){
naglowek > instaluj.sh
instaluj_gcc instaluj_nowy >> instaluj.sh
instalacja gcc
}

nv_radeon(){
if lspci | grep -i GeForce | grep -i NVIDIA;then
	a5="TRUE"
else
	a5="FALSE"
fi
if ! lspci | grep VGA | awk '{print tolower($0)}' | grep radeon || [ "$(glxinfo | grep 'AMD Radeon HD' | sed -e 's/.*HD //g' -e 's/ .*//g')" -le 5000 ];then
	a6="FALSE"
else
	a6="TRUE"
fi
}

aktualizuj_calosc(){
nv_radeon
konfiguracja=$(yad --center --title="$nazwa_skryptu" --on-top --window-icon="/opt/NeteXt73/ikony/start.png" --image="/opt/NeteXt73/ikony/start.png" --text="<span color=\"$kolor_textu\">$TEXT_UPDATE1</span>" --center --form --columns=3 --field="system microcode:CHK" --field="grub:CHK" --field="apm:CHK" --field="kernel:CHK" --field="NVIDIA:CHK" --field="Mesa3D:CHK" --field="gcc:CHK"  $a1 $a2 $a3 $a4 $a5 $a6 $a7 --width="$((650*$skala))" --button="gtk-ok:0" --button="$TEXT_POWROT:1" )
	klawisz=$?
	if [ "$klawisz" = "0" ]; then
		if [ "$(echo $konfiguracja | cut -d '|' -f 1 )" = "TRUE" ]; then
			/opt/NeteXt73/./microcode
		fi
		if [ "$(echo $konfiguracja | cut -d '|' -f 2 )" = "TRUE" ]; then
			/opt/NeteXt73/./grub
		fi
		if [ "$(echo $konfiguracja | cut -d '|' -f 3 )" = "TRUE" ]; then
			/opt/NeteXt73/./apm
		fi
		if [ "$(echo $konfiguracja | cut -d '|' -f 5 )" = "TRUE" ]; then
			/opt/NeteXt73/./grafiki nvidia
		fi
		if [ "$(echo $konfiguracja | cut -d '|' -f 6 )" = "TRUE" ]; then
			/opt/NeteXt73/./grafiki mesa3d
		fi
		if [ "$(echo $konfiguracja | cut -d '|' -f 7 )" = "TRUE" ]; then
			instalacja_gcc
		fi
		if [ "$(echo $konfiguracja | cut -d '|' -f 4 )" = "TRUE" ]; then
			if [ "$kernel_premium" = "tak" ]; then
				/opt/NeteXt73/./kernele premium
			else
				/opt/NeteXt73/./kernele standard
			fi
		fi

	fi
}
usun

#firmware
stan_firmware
twoj_firmware=$(dpkg -l | grep linux-firmware | awk '{print $3}' | head -n 1 | sed 's/~.*//')

#microcode
if [ "$stan_microcode" = "-" ]; then
	firm=$TEXT_UPDATE5a
	a1="TRUE"
	TEXT_DYMKA="\nFirmware - $TEXT_UPDATE5a"
else
	firm=v$twoj_firmware
	a1="FALSE"
fi

#GRUB
if [ "$(grep 'acpi_osi=' /etc/default/grub)" = "" ] || [ "$(grep '915.lvds_downclock=1' /etc/default/grub)" != "" ] || [ "$(grep 'i915.semaphores=1' /etc/default/grub)" != "" ] ; then
	a2="TRUE"
	TEXT_DYMKA="$TEXT_DYMKA\nGRUB - $TEXT_UPDATE5a"
else
	a2="FALSE"
fi

#APM
stan_apm #sprawdzenie stanu instalacji
twoj_apm=$(ls $katalog_apm | cut -d "_" -f 7 | head -n 1)
if [ "$stan_apm" != "-" ]; then
	apm="$TEXT_UPDATE4"
	a3="FALSE"
else
	apm="$TEXT_UPDATE5 $wersja_apm"
	a3="TRUE"
	TEXT_DYMKA="$TEXT_DYMKA\nAPM - $TEXT_UPDATE5a"
fi


#kernel zainstalowany
sprawdz_kernel

if [ "$(cat /tmp/netext73/sumy/kernel*.txt)" = "" ]; then
	kern=$TEXT_BRAK_DANYCH
	a4="TRUE"
	TEXT_DYMKA="$TEXT_DYMKA\nKERNEL - $TEXT_UPDATE5a"
else
	if [ "$(dpkg -l |grep linux-image | awk '{print $2}' | sed 's/linux-image-//g' | grep $kern2)" != "" ]; then
		kern="$TEXT_UPDATE4"
		a4="FALSE"
	else
		kern="$TEXT_UPDATE5 v$(echo $nowy_kernel | sed 's/_testowy.*//g' | sed 's/_stabilny.*//g' | cut -d "-" -f 3)"
		a4="TRUE"
		TEXT_DYMKA="$TEXT_DYMKA\nKERNEL - $TEXT_UPDATE5a"
	fi
	if [ "$(dpkg -l |grep linux-image | awk '{print $2}' | sed 's/linux-image-//g' | grep $kern2)" != "" ] && [ "$kern1" != "$(echo $twoj_kernel | sed 's/.*v//')" ]; then
		kern="$TEXT_UPDATE9"
		a4="FALSE"
	fi
fi

#gcc
twoj_gcc=$(gcc --version | head -n 1 | awk '{print $3}')
dostepny_gcc=$(ls /opt/NeteXt73-pakiety/pakiety/ | grep gcc | cut -d "-" -f 2 | sed 's/.tar.xz//g')
if [ "$twoj_gcc" = "$dostepny_gcc" ];then
	gcc_text="$twoj_gcc"
	a7="FALSE"
else
	gcc_text="$TEXT_UPDATE5a V$dostepny_gcc"
	a7="TRUE"
	TEXT_DYMKA="$TEXT_DYMKA\nGCC - $TEXT_UPDATE5a"
fi

#dymek możliwych aktualizacji
if [ "$TEXT_DYMKA" != "" ]; then
	dymek -i $ikona_info1 "$TEXT_UWAGA" "$TEXT_DYMKA"
fi
if [ "$1" = "first" ]; then
	if [ ! -e ~/.netext73/opis_programu ]; then
		/opt/NeteXt73/./help & #odpalenie strony z opisem
		echo "TRUE" > ~/.netext73/opis_programu
	fi
	a1="TRUE"
	a2="TRUE"
	a3="TRUE"
	a4="TRUE"
	#a7 zaznaczone na podstawie stanu gcc
	nv_radeon
	aktualizuj_calosc
	usun
	exit 0
fi

if [ "$1" != "start" ]; then
	if [ "$(echo $a1$a2$a3$a4$a7 | grep 'TRUE')" != "" ];then
		menu="$TEXT_UPDATE8!$TEXT_UPDATE7!$TEXT_UPDATE2"
	else
		menu="$TEXT_UPDATE2!$TEXT_UPDATE7!$TEXT_UPDATE8"
	fi

	a=$(yad --center --on-top --title="$nazwa_skryptu" --width=$((680*$skala)) --window-icon="/opt/NeteXt73/ikony/update.png" --image="/opt/NeteXt73/ikony/update.png" --form \
	--field="Firmware/microcode:RO" "$firm" \
	--field="Kernel $twoj_kernel:RO" "$kern" \
	--field="APM $twoj_apm:RO" "$apm" \
	--field="gcc -version:RO" "$(gcc --version | head -n 1)" \
	--field="$TEXT_UPDATE1:CB" "$menu" \
	--button="gtk-ok:0" \
	--button="$(echo $TEXT_SUMY_KONTROLNE | tr '_' ' '):3" --button="$TEXT_ZAMKNIJ:1")
	klawisz=$?; a=$(echo $a | cut -d "|" -f 5)

	if [ $klawisz = "0" ]; then
		if [ "$a" = "$TEXT_UPDATE2" ]; then
			if [ -e ~/.netext73/clean ] && [ "$(grep TRUE ~/.netext73/clean)" = "" ] || [ ! -e ~/.netext73/clean ]; then
				xterm -T  "dist-upgrade" -e bash -c "echo 'sudo apt update && sudo apt dist-upgrade'; sudo apt update && sudo apt dist-upgrade -y;echo -e \"$TEXT_INSTALACJA2\"; read ent"
			elif [ -e ~/.netext73/clean ] && [ "$(grep TRUE ~/.netext73/clean)" != "" ]; then
				xterm -T  "dist-upgrade & clean" -e bash -c "echo 'sudo apt update && sudo apt dist-upgrade && sudo apt autoclean && sudo apt autoremove'; sudo apt update && sudo apt dist-upgrade -y && sudo apt autoclean && sudo apt autoremove ; echo -e \"$TEXT_INSTALACJA2\"; read ent"	
			fi
		elif [ "$a" = "$TEXT_UPDATE8" ]; then
			aktualizuj_calosc
		elif [ "$a" = "$TEXT_UPDATE7" ]; then
			a1="TRUE"
			a2="TRUE"
			a3="TRUE"
			a4="TRUE"
			a7="TRUE"
			aktualizuj_calosc
		fi
	elif [ "$klawisz" = "3" ]; then
		rm -f /tmp/netext73/sumy/*
		/opt/NeteXt73/./update start &
	fi
fi
usun
