#!/bin/bash
## Graficzny instalator kerneli e X t 7 3  - NeteXt'73
## przygotowanie kerneli e X t 7 3 - ext73@wp.pl
## przygotowanie skryptów optymalizacyjnych e X t 7 3
## autor skryptu NeteXt'73 - NetBit73 - netbit73@gmail.com
## Licencja: GPL v3: https://www.gnu.org/licenses/gpl.txt
########################################################################################################################
if [ "$1" = "2" ]; then
	#!/bin/bash
	if [ -e /opt/NeteXt73/pakiety/gcc* ]; then
		mkdir -p /tmp/gcc
		rm -f /tmp/gcc/gcc*
		cp /opt/NeteXt73/pakiety/gcc* /tmp/gcc/ -f
		rm -f /opt/NeteXt73/pakiety/gcc*
	fi	
	git add -A
	IFS=$'\n'
	echo 'podaj komentarz:'
	read a
	git commit -m $a
	git push origin master
	if [ -e  /tmp/gcc/gcc* ]; then
		cp /tmp/gcc/gcc* /opt/NeteXt73/pakiety  -f
		rm -rf /tmp/gcc
	fi	
else
	LATEST_VERSION=$(grep 'v[0-9]' changelog | head -n 1 | cut -d 'v' -f 2)
	PKG_NAME="netext73"
	dch --controlmaint --distribution xenial -v $LATEST_VERSION --package netext73
	./zmiany 2
fi

