#!/bin/bash
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################
#wyłączenie historycznych elementów apm_ext73
if [ ! -e /usr/lib/pm-utils/power.d/wireless ];then
	sudo cp /opt/NeteXt73/APM/wireless /usr/lib/pm-utils/power.d/
fi

if [ ! -e /usr/lib/pm-utils/power.d/laptop-mode ];then
	sudo cp /opt/NeteXt73/APM/laptop-mode /usr/lib/pm-utils/power.d/
fi

#wyłączenie bfq jak kernel go nie posiada
if [ "$(grep bfq /sys/block/sd*/queue/scheduler)" = "" ]; then
	if [ -e /etc/apm-ext73 ] && [ "$(ls /etc/apm-ext73 | grep advanced_power_management_by_ext73)" != "" ]; then
		sudo sed -i '/#HDD/ s/bfq/cfq/g' /etc/apm-ext73/advanced_power_management_by_ext73_*
	elif [ -e /etc/pm/power.d ] && [ "$(ls /etc/pm/power.d | grep advanced_power_management_by_ext73)" != "" ]; then
		sudo sed -i '/#HDD/ s/bfq/cfq/g' /etc/pm/power.d/advanced_power_management_by_ext73_*
	fi
fi
#binutils
if [ "$(ld -v | grep -i ext)" = "" ]; then
	wersja_binutils=$(ls /opt/NeteXt73-pakiety/pakiety/ | grep binutils | cut -d "-" -f 2 | sed 's/.tar.xz//g')
        tar -Jxf /opt/NeteXt73-pakiety/pakiety/$(ls /opt/NeteXt73-pakiety/pakiety | grep binutils) -C /opt/
        ln -sf /opt/binutils-$wersja_binutils/bin/ld /usr/bin/ld
        ln -sf /opt/binutils-$wersja_binutils/bin/ld /usr/bin/ld-plugin
        ln -sf /opt/binutils-$wersja_binutils/bin/ld.bfd /usr/bin/ld.bfd
fi
