#!/bin/bash
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################

#wyłączenie bfq jak kernel go nie posiada
if [ "$(grep bfq /sys/block/sd*/queue/scheduler)" = "" ]; then
	if [ -e /etc/apm-ext73 ] && [ "$(ls /etc/apm-ext73 | grep advanced_power_management_by_ext73)" != "" ]; then
		sudo sed -i '/#HDD/ s/bfq/cfq/g' /etc/apm-ext73/advanced_power_management_by_ext73_*
	elif [ -e /etc/pm/power.d ] && [ "$(ls /etc/pm/power.d | grep advanced_power_management_by_ext73)" != "" ]; then
		sudo sed -i '/#HDD/ s/bfq/cfq/g' /etc/pm/power.d/advanced_power_management_by_ext73_*
	fi
fi
#binutils i gcc
if [ "$(ld -v | grep -i ubuntu)" != "" ] || [ "$(gcc --version | grep -i ext73)" = "" ]; then
	tar -Jxf /opt/NeteXt73-pakiety/pakiety/$(ls /opt/NeteXt73-pakiety/pakiety | grep gcc) -C /opt/
	tar -Jxf /opt/NeteXt73-pakiety/pakiety/$(ls /opt/NeteXt73-pakiety/pakiety | grep binutils) -C /opt/
	ln -sf /opt/binutils-$(ls /opt/NeteXt73-pakiety/pakiety/ | grep binutils | cut -d "-" -f 2 | sed 's/.tar.xz//g')/bin/ld /usr/bin/ld
	ln -sf /opt/binutils-$(ls /opt/NeteXt73-pakiety/pakiety/ | grep binutils | cut -d "-" -f 2 | sed 's/.tar.xz//g')/bin/ld /usr/bin/ld-plugin
	ln -sf /opt/binutils-$(ls /opt/NeteXt73-pakiety/pakiety/ | grep binutils | cut -d "-" -f 2 | sed 's/.tar.xz//g')/bin/ld.bfd /usr/bin/ld.bfd
	ln -sf /opt/gcc-$(ls /opt/NeteXt73-pakiety/pakiety/ | grep gcc | cut -d "-" -f 2 | sed 's/.tar.xz//g')/bin/gcc /usr/bin/gcc
	ln -sf /opt/gcc-$(ls /opt/NeteXt73-pakiety/pakiety/ | grep gcc | cut -d "-" -f 2 | sed 's/.tar.xz//g')/bin/gcc-ar /usr/bin/gcc-ar
	ln -sf /opt/gcc-$(ls /opt/NeteXt73-pakiety/pakiety/ | grep gcc | cut -d "-" -f 2 | sed 's/.tar.xz//g')/bin/cpp /usr/bin/cpp
	ln -sf /opt/gcc-$(ls /opt/NeteXt73-pakiety/pakiety/ | grep gcc | cut -d "-" -f 2 | sed 's/.tar.xz//g')/bin/g++ /usr/bin/g++
	ln -sf /opt/gcc-$(ls /opt/NeteXt73-pakiety/pakiety/ | grep gcc | cut -d "-" -f 2 | sed 's/.tar.xz//g')/bin/c++ /usr/bin/c++
	ldconfig
	rm /usr/lib/x86_64-linux-gnu/libisl.so.10
	ln -sf /usr/lib/x86_64-linux-gnu/libisl.so.13 /usr/lib/x86_64-linux-gnu/libisl.so.10
fi
#TPC
if [ -e /etc/sysctl.conf ]; then
	if [ "$(grep 'net.ipv4.tcp_challenge_ack_limit = 999999999' /etc/sysctl.conf)" = "" ]; then
		echo 'net.ipv4.tcp_challenge_ack_limit = 999999999' >> /etc/sysctl.conf
		sysctl -p
	fi
fi
#linkowanie
plik=$(ls /opt/gcc-$(gcc --version | grep -i ext73 | awk '{print $3}')/lib64 | grep libstdc++.so.6. | grep -v gdb.py)
wersja=$(gcc --version | grep -i ext73 | awk '{print $3}')
if [ "$(uname -a | grep ext73)" != "" ] && [ "$(gcc --version | grep -i ext73)" != "" ]; then
	if [ ! -e /usr/lib/x86_64-linux-gnu/$plik ] || [ "$(md5sum /usr/lib/x86_64-linux-gnu/$plik | awk '{print $1}')" != "$(md5sum /usr/lib/x86_64-linux-gnu/$plik | awk '{print $1}')" ]; then
		rm /usr/lib/x86_64-linux-gnu/$plik -f
		cp /opt/gcc-$wersja/lib64/$plik /usr/lib/x86_64-linux-gnu/ -f
		if [ "$(ls -la /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep $plik)" = "" ]; then
			rm /usr/lib/x86_64-linux-gnu/libstdc++.so.6 -f
			ln -sf /usr/lib/x86_64-linux-gnu/$plik /usr/lib/x86_64-linux-gnu/libstdc++.so.6
		fi
		ldconfig
	fi
	#linkowanie steam
	if [ -e /home/*/.local/share/Steam/ ]; then 
		rm -f /home/*/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libstdc++.so.6
		cp -f /opt/gcc-$wersja/lib64/$plik /home/*/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/
		cp -f /opt/gcc-$wersja/lib64/libstdc++.so.6 /home/*/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/
	fi
else
	rm /usr/lib/x86_64-linux-gnu/$plik -f
	rm /usr/lib/x86_64-linux-gnu/libstdc++.so.6 -f
	ln -sf /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21 /usr/lib/x86_64-linux-gnu/libstdc++.so.6
	ldconfig
	#linkowanie steam
	if [ -e /home/*/.local/share/Steam/ ]; then 
		rm -f /home/*/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libstdc++.so.6
		rm -f /home/*/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/$plik
	fi	
fi
