#!/bin/bash
#		    _   _      _      __  ___   _ _____ _____
#		   | \ | | ___| |_ ___\ \/ / |_( )___  |___ /
#		   |  \| |/ _ \ __/ _ \\  /| __|/   / /  |_ \
#		   | |\  |  __/ |_  __//  \| |_    / /  ___) |
#		   |_| \_|\___|\__\___/_/\_\\__|  /_/  |____/
#
#	            __ _ _ __ __ _ / _(_) ___ _____ __  _   _
#	           / _` | '__/ _` | |_| |/ __|_  / '_ \| | | |
#	          | (_| | | | (_| |  _| | (__ / /| | | | |_| |
#	           \__, |_|  \__,_|_| |_|\___/___|_| |_|\__, |
#	           |___/                                |___/
#     _           _        _       _                   _                        _ _
#    (_)_ __  ___| |_ __ _| | __ _| |_ ___  _ __      | | _____ _ __ _ __   ___| (_)
#    | | '_ \/ __| __/ _` | |/ _` | __/ _ \| '__|     | |/ / _ \ '__| '_ \ / _ \ | |
#    | | | | \__ \ |_ (_| | | (_| | |_ (_) | |        |   <  __/ |  | | | |  __/ | |
#    |_|_| |_|___/\__\__,_|_|\__,_|\__\___/|_|        |_|\_\___|_|  |_| |_|\___|_|_|
#        __  __  _     _____   _____      ___     _   _      _   ____  _ _  _____ ____
#   ___  \ \/ / | |_  |___  | |___ /     ( _ )   | \ | | ___| |_| __ )(_) |____  |___ /
#  / _ \  \  /  | __|    / /    |_ \     / _ \/\ |  \| |/ _ \ __|  _ \| | __| / /  |_ \
# |  __/  /  \  | |_    / /    ___) |   | (_>  < | |\  |  __/ |_| |_) | | |_ / /  ___) |
#  \___| /_/\_\  \__|  /_/    |____/     \___/\/ |_| \_|\___|\__|____/|_|\__/_/  |____/
#
#########################################################################################################################################################################


#binutils i gcc
if [ "$(ld -v | grep -i ubuntu)" != "" ] || [ "$(gcc --version | grep -i ext73)" = "" ]; then
#procedury
	mkdir -p /tmp/netext73
	cd /tmp/netext73
	source /opt/NeteXt73/procedury
	naglowek > instaluj.sh
	instaluj_gcc instaluj_nowy >> instaluj.sh
	bash instaluj.sh
	rm -rf /tmp/netext73
fi
#TPC
if [ -e /etc/sysctl.conf ]; then
	if [ "$(grep 'net.ipv4.tcp_challenge_ack_limit = 999999999' /etc/sysctl.conf)" = "" ]; then
		echo 'net.ipv4.tcp_challenge_ack_limit = 999999999' >> /etc/sysctl.conf
		sysctl -p
	fi
fi
#linkowanie
wersja=$(gcc --version | grep -i ext73 | awk '{print $3}')
plik=$(ls /opt/gcc-$wersja/lib64 | grep libstdc++.so.6. | grep -v gdb.py | sort -r | head -n 1)
suma=$(md5sum /opt/gcc-$wersja/lib64/$plik | awk '{print $1}')
if [ "$(uname -a | grep -i ext73)" != "" ] && [ "$(gcc --version | grep -i ext73)" != "" ]; then
	if [ ! -e /usr/lib/x86_64-linux-gnu/$plik ] || [ "$(md5sum /usr/lib/x86_64-linux-gnu/$plik | awk '{print $1}')" != "$suma" ] || [ ! -e /usr/lib/x86_64-linux-gnu/libstdc++.so.6 ]; then
		rm /usr/lib/x86_64-linux-gnu/$plik -f
		cp /opt/gcc-$wersja/lib64/$plik /usr/lib/x86_64-linux-gnu/ -f
		rm /usr/lib/x86_64-linux-gnu/libstdc++.so.6 -f
		ln -sf /usr/lib/x86_64-linux-gnu/$plik /usr/lib/x86_64-linux-gnu/libstdc++.so.6
		ldconfig
	fi
#linkowanie steam
	if [ -e /home/*/.local/share/Steam/ ]; then
		rm -f /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22 
		rm -f /home/*/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libstdc++.so.6
		cp -f /opt/gcc-$wersja/lib64/libstdc++.so.6.0.22 /usr/lib/x86_64-linux-gnu/ 
		cp -f /opt/gcc-$wersja/lib64/libstdc++.so.6.0.22 /home/*/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/
		cp -f /opt/gcc-$wersja/lib64/libstdc++.so.6 /home/*/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/
		cp -f /opt/gcc-$wersja/lib64/$plik /home/*/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/
	fi
else
	rm /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22 -f
	rm /usr/lib/x86_64-linux-gnu/libstdc++.so.6 -f
	ln -sf /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21 /usr/lib/x86_64-linux-gnu/libstdc++.so.6
	ldconfig
	#linkowanie steam
	if [ -e /home/*/.local/share/Steam/ ]; then
		rm -f /home/*/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libstdc++.so.6
		rm -f /home/*/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
	fi
fi

#nvidia fix
if [ "$(lspci | grep -i VGA | grep -i Intel)" != "" ] && [ "$(lspci | grep -i GeForce | grep -i NVIDIA)" != "" ];then
	#procedury
	mkdir -p /tmp/netext73
	cd /tmp/netext73
	source /opt/NeteXt73/procedury
	if [ "$(lsb_release -a | grep -E "$wspierane_nr")" != "" ] || [ "$(echo $WERSJA_UBUNTU | grep -i -x -E "$wspierane_wersje")" != "" ]; then
		rm -f /etc/alternatives/x86_64-linux-gnu_nvidia_modconf
		rm -f /etc/modprobe.d/nvidia-graphics-drivers.conf
		rm -f /etc/ld.so.conf.d/i386-linux-gnu_GL.conf
		rm -f /etc/alternatives/i386-linux-gnu_xorg_extra_modules
		rm -f /etc/alternatives/x86_64-linux-gnu_xorg_extra_modules
		rm -f /etc/ld.so.conf.d/x86_64-linux-gnu_GL.conf
		ln -sf /usr/lib/i386-linux-gnu/mesa/ld.so.conf /etc/alternatives/i386-linux-gnu_gl_conf
		ln -sf /usr/lib/i386-linux-gnu/mesa/ld.so.conf /etc/ld.so.conf.d/i386-linux-gnu_GL.conf
		ln -sf /usr/lib/i386-linux-gnu/xorg/x11-extra-modules/ /etc/alternatives/i386-linux-gnu_xorg_extra_modules
		ln -sf /usr/lib/x86_64-linux-gnu/mesa/ld.so.conf /etc/alternatives/x86_64-linux-gnu_gl_conf
		ln -sf /usr/lib/x86_64-linux-gnu/mesa/ld.so.conf /etc/ld.so.conf.d/x86_64-linux-gnu_GL.conf
		ln -sf /usr/lib/x86_64-linux-gnu/mesa-egl/ld.so.conf /etc/ld.so.conf.d/x86_64-linux-gnu_EGL.conf
		ln -sf /usr/lib/x86_64-linux-gnu/xorg/x11-extra-modules/ /etc/alternatives/x86_64-linux-gnu_xorg_extra_modules
		ldconfig
	fi
	rm -rf /tmp/netext73
fi

